# coding: utf-8

"""
    Okta API

    Allows customers to easily access the Okta API

    The version of the OpenAPI document: 2.16.0
    Contact: devex-public@okta.com
    Created by: https://developer.okta.com/
"""

from okta_python_sdk.paths.api_v1_authenticators_authenticator_id_lifecycle_activate.post import ActivateLifecycleSuccess
from okta_python_sdk.paths.api_v1_authenticators.post import CreateNew
from okta_python_sdk.paths.api_v1_authenticators_authenticator_id_lifecycle_deactivate.post import DeactivateLifecycleSuccess
from okta_python_sdk.paths.api_v1_authenticators_authenticator_id.get import GetSuccess
from okta_python_sdk.paths.api_v1_authenticators.get import ListAllAvailable
from okta_python_sdk.paths.api_v1_authenticators_authenticator_id.put import UpdateAuthenticator
from okta_python_sdk.apis.tags.authenticator_api_raw import AuthenticatorApiRaw


class AuthenticatorApi(
    ActivateLifecycleSuccess,
    CreateNew,
    DeactivateLifecycleSuccess,
    GetSuccess,
    ListAllAvailable,
    UpdateAuthenticator,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    raw: AuthenticatorApiRaw

    def __init__(self, api_client=None):
        super().__init__(api_client)
        self.raw = AuthenticatorApiRaw(api_client)
