# coding: utf-8

"""
    Okta API

    Allows customers to easily access the Okta API

    The version of the OpenAPI document: 2.16.0
    Contact: devex-public@okta.com
    Created by: https://developer.okta.com/
"""

from okta_python_sdk.paths.api_v1_brands_brand_id_templates_email_template_name_customizations.post import CreateEmailTemplateCustomization
from okta_python_sdk.paths.api_v1_brands_brand_id_templates_email_template_name_customizations_customization_id.delete import DeleteEmailCustomization
from okta_python_sdk.paths.api_v1_brands_brand_id_templates_email_template_name_customizations.delete import DeleteEmailTemplateCustomizations
from okta_python_sdk.paths.api_v1_brands_brand_id_themes_theme_id_background_image.delete import DeleteThemeBackgroundImage
from okta_python_sdk.paths.api_v1_brands_brand_id_themes_theme_id_favicon.delete import DeleteThemeFavicon
from okta_python_sdk.paths.api_v1_brands_brand_id_themes_theme_id_logo.delete import DeleteThemeLogo
from okta_python_sdk.paths.api_v1_brands.get import GetAllBrands
from okta_python_sdk.paths.api_v1_brands_brand_id.get import GetById
from okta_python_sdk.paths.api_v1_brands_brand_id_templates_email_template_name_customizations_customization_id_preview.get import GetEmailCustomizationPreview
from okta_python_sdk.paths.api_v1_brands_brand_id_templates_email_template_name.get import GetEmailTemplate
from okta_python_sdk.paths.api_v1_brands_brand_id_templates_email_template_name_customizations_customization_id.get import GetEmailTemplateCustomizationById
from okta_python_sdk.paths.api_v1_brands_brand_id_templates_email_template_name_default_content.get import GetEmailTemplateDefaultContent
from okta_python_sdk.paths.api_v1_brands_brand_id_templates_email_template_name_default_content_preview.get import GetEmailTemplateDefaultContentPreview
from okta_python_sdk.paths.api_v1_brands_brand_id_templates_email_template_name_test.post import GetEmailTemplateDefaultContentPreview0
from okta_python_sdk.paths.api_v1_brands_brand_id_themes_theme_id.get import GetThemeById
from okta_python_sdk.paths.api_v1_brands_brand_id_themes.get import GetThemes
from okta_python_sdk.paths.api_v1_brands_brand_id_templates_email_template_name_customizations.get import ListEmailTemplateCustomizations
from okta_python_sdk.paths.api_v1_brands_brand_id_templates_email.get import ListEmailTemplates
from okta_python_sdk.paths.api_v1_brands_brand_id.put import UpdateByBrandId
from okta_python_sdk.paths.api_v1_brands_brand_id_templates_email_template_name_customizations_customization_id.put import UpdateEmailCustomization
from okta_python_sdk.paths.api_v1_brands_brand_id_themes_theme_id.put import UpdateTheme
from okta_python_sdk.paths.api_v1_brands_brand_id_themes_theme_id_background_image.post import UpdateThemeBackgroundImage
from okta_python_sdk.paths.api_v1_brands_brand_id_themes_theme_id_favicon.post import UpdateThemeFavicon
from okta_python_sdk.paths.api_v1_brands_brand_id_themes_theme_id_logo.post import UpdateThemeLogo
from okta_python_sdk.apis.tags.brand_api_raw import BrandApiRaw


class BrandApi(
    CreateEmailTemplateCustomization,
    DeleteEmailCustomization,
    DeleteEmailTemplateCustomizations,
    DeleteThemeBackgroundImage,
    DeleteThemeFavicon,
    DeleteThemeLogo,
    GetAllBrands,
    GetById,
    GetEmailCustomizationPreview,
    GetEmailTemplate,
    GetEmailTemplateCustomizationById,
    GetEmailTemplateDefaultContent,
    GetEmailTemplateDefaultContentPreview,
    GetEmailTemplateDefaultContentPreview0,
    GetThemeById,
    GetThemes,
    ListEmailTemplateCustomizations,
    ListEmailTemplates,
    UpdateByBrandId,
    UpdateEmailCustomization,
    UpdateTheme,
    UpdateThemeBackgroundImage,
    UpdateThemeFavicon,
    UpdateThemeLogo,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    raw: BrandApiRaw

    def __init__(self, api_client=None):
        super().__init__(api_client)
        self.raw = BrandApiRaw(api_client)
