# coding: utf-8

"""
    Okta API

    Allows customers to easily access the Okta API

    The version of the OpenAPI document: 2.16.0
    Contact: devex-public@okta.com
    Created by: https://developer.okta.com/
"""

from okta_python_sdk.paths.api_v1_features_feature_id_lifecycle.post import CreateLifecycleSuccess
from okta_python_sdk.paths.api_v1_features.get import GetSuccess
from okta_python_sdk.paths.api_v1_features_feature_id.get import GetSuccessById
from okta_python_sdk.paths.api_v1_features_feature_id_dependencies.get import ListDependencies
from okta_python_sdk.paths.api_v1_features_feature_id_dependents.get import ListDependents
from okta_python_sdk.apis.tags.feature_api_raw import FeatureApiRaw


class FeatureApi(
    CreateLifecycleSuccess,
    GetSuccess,
    GetSuccessById,
    ListDependencies,
    ListDependents,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    raw: FeatureApiRaw

    def __init__(self, api_client=None):
        super().__init__(api_client)
        self.raw = FeatureApiRaw(api_client)
