# coding: utf-8

"""
    Okta API

    Allows customers to easily access the Okta API

    The version of the OpenAPI document: 2.16.0
    Contact: devex-public@okta.com
    Created by: https://developer.okta.com/
"""

from okta_python_sdk.paths.api_v1_meta_schemas_group_default.get import GetRaw
from okta_python_sdk.paths.api_v1_meta_schemas_group_default.post import UpdateCustomPropertiesRaw


class GroupSchemaApiRaw(
    GetRaw,
    UpdateCustomPropertiesRaw,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    pass
