# coding: utf-8

"""
    Okta API

    Allows customers to easily access the Okta API

    The version of the OpenAPI document: 2.16.0
    Contact: devex-public@okta.com
    Created by: https://developer.okta.com/
"""

from okta_python_sdk.paths.api_v1_meta_schemas_user_linked_objects.post import CreateLinkedObjectRaw
from okta_python_sdk.paths.api_v1_meta_schemas_user_linked_objects_linked_object_name.delete import DeleteUserLinkedObjectRaw
from okta_python_sdk.paths.api_v1_meta_schemas_user_linked_objects.get import GetUserLinkedObjectsRaw
from okta_python_sdk.paths.api_v1_meta_schemas_user_linked_objects_linked_object_name.get import GetUserLinkedObjects0Raw


class LinkedObjectApiRaw(
    CreateLinkedObjectRaw,
    DeleteUserLinkedObjectRaw,
    GetUserLinkedObjectsRaw,
    GetUserLinkedObjects0Raw,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    pass
