# coding: utf-8

"""
    Okta API

    Allows customers to easily access the Okta API

    The version of the OpenAPI document: 2.16.0
    Contact: devex-public@okta.com
    Created by: https://developer.okta.com/
"""

from okta_python_sdk.paths.api_v1_org_privacy_okta_support_extend.post import ExtendOktaSupport
from okta_python_sdk.paths.api_v1_org_privacy_okta_support_revoke.post import ExtendOktaSupport0
from okta_python_sdk.paths.api_v1_org_contacts_contact_type.get import GetContactUser
from okta_python_sdk.paths.api_v1_org_privacy_okta_communication.get import GetOktaCommunicationSettings
from okta_python_sdk.paths.api_v1_org_privacy_okta_support.get import GetOktaSupportSettings
from okta_python_sdk.paths.api_v1_org_preferences.get import GetOrgPreferences
from okta_python_sdk.paths.api_v1_org.get import GetSettings
from okta_python_sdk.paths.api_v1_org_privacy_okta_support_grant.post import GrantOktaSupportAccess
from okta_python_sdk.paths.api_v1_org_preferences_hide_end_user_footer.post import HideEndUserFooter
from okta_python_sdk.paths.api_v1_org_contacts.get import ListContactTypes
from okta_python_sdk.paths.api_v1_org_preferences_show_end_user_footer.post import MakeOktaUiFooterVisible
from okta_python_sdk.paths.api_v1_org_privacy_okta_communication_opt_in.post import OptInOktaCommunicationEmails
from okta_python_sdk.paths.api_v1_org_privacy_okta_communication_opt_out.post import OptOutOktaCommunicationEmails
from okta_python_sdk.paths.api_v1_org_contacts_contact_type.put import UpdateContactUser
from okta_python_sdk.paths.api_v1_org_logo.post import UpdateOrganizationLogo
from okta_python_sdk.paths.api_v1_org.put import UpdateSetting
from okta_python_sdk.paths.api_v1_org.post import UpdateSettings
from okta_python_sdk.apis.tags.org_api_raw import OrgApiRaw


class OrgApi(
    ExtendOktaSupport,
    ExtendOktaSupport0,
    GetContactUser,
    GetOktaCommunicationSettings,
    GetOktaSupportSettings,
    GetOrgPreferences,
    GetSettings,
    GrantOktaSupportAccess,
    HideEndUserFooter,
    ListContactTypes,
    MakeOktaUiFooterVisible,
    OptInOktaCommunicationEmails,
    OptOutOktaCommunicationEmails,
    UpdateContactUser,
    UpdateOrganizationLogo,
    UpdateSetting,
    UpdateSettings,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    raw: OrgApiRaw

    def __init__(self, api_client=None):
        super().__init__(api_client)
        self.raw = OrgApiRaw(api_client)
