# coding: utf-8

"""
    Okta API

    Allows customers to easily access the Okta API

    The version of the OpenAPI document: 2.16.0
    Contact: devex-public@okta.com
    Created by: https://developer.okta.com/
"""

from okta_python_sdk.paths.api_v1_policies_policy_id_lifecycle_activate.post import ActivateLifecycleRaw
from okta_python_sdk.paths.api_v1_policies_policy_id_rules_rule_id_lifecycle_activate.post import ActivateRuleLifecycleRaw
from okta_python_sdk.paths.api_v1_policies.post import CreateNewPolicyRaw
from okta_python_sdk.paths.api_v1_policies_policy_id_rules.post import CreateRuleRaw
from okta_python_sdk.paths.api_v1_policies_policy_id_lifecycle_deactivate.post import DeactivateLifecycleRaw
from okta_python_sdk.paths.api_v1_policies_policy_id_rules_rule_id_lifecycle_deactivate.post import DeactivateRuleLifecycleRaw
from okta_python_sdk.paths.api_v1_policies_policy_id_rules.get import EnumerateRulesRaw
from okta_python_sdk.paths.api_v1_policies.get import GetAllWithTypeRaw
from okta_python_sdk.paths.api_v1_policies_policy_id.get import GetPolicyRaw
from okta_python_sdk.paths.api_v1_policies_policy_id_rules_rule_id.get import GetPolicyRuleRaw
from okta_python_sdk.paths.api_v1_policies_policy_id.delete import RemovePolicyOperationRaw
from okta_python_sdk.paths.api_v1_policies_policy_id_rules_rule_id.delete import RemoveRuleRaw
from okta_python_sdk.paths.api_v1_policies_policy_id.put import UpdateOperationRaw
from okta_python_sdk.paths.api_v1_policies_policy_id_rules_rule_id.put import UpdateRuleRaw


class PolicyApiRaw(
    ActivateLifecycleRaw,
    ActivateRuleLifecycleRaw,
    CreateNewPolicyRaw,
    CreateRuleRaw,
    DeactivateLifecycleRaw,
    DeactivateRuleLifecycleRaw,
    EnumerateRulesRaw,
    GetAllWithTypeRaw,
    GetPolicyRaw,
    GetPolicyRuleRaw,
    RemovePolicyOperationRaw,
    RemoveRuleRaw,
    UpdateOperationRaw,
    UpdateRuleRaw,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    pass
