# coding: utf-8

"""
    Okta API

    Allows customers to easily access the Okta API

    The version of the OpenAPI document: 2.16.0
    Contact: devex-public@okta.com
    Created by: https://developer.okta.com/
"""

from okta_python_sdk.paths.api_v1_mappings_mapping_id.get import GetByIdRaw
from okta_python_sdk.paths.api_v1_mappings.get import ListWithPaginationRaw
from okta_python_sdk.paths.api_v1_mappings_mapping_id.post import UpdatePropertyMappingsRaw


class ProfileMappingApiRaw(
    GetByIdRaw,
    ListWithPaginationRaw,
    UpdatePropertyMappingsRaw,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    pass
