# coding: utf-8

"""
    Okta API

    Allows customers to easily access the Okta API

    The version of the OpenAPI document: 2.16.0
    Contact: devex-public@okta.com
    Created by: https://developer.okta.com/
"""

from okta_python_sdk.paths.api_v1_mappings_mapping_id.get import GetById
from okta_python_sdk.paths.api_v1_mappings.get import ListWithPagination
from okta_python_sdk.paths.api_v1_mappings_mapping_id.post import UpdatePropertyMappings
from okta_python_sdk.apis.tags.profile_mapping_api_raw import ProfileMappingApiRaw


class ProfileMappingApi(
    GetById,
    ListWithPagination,
    UpdatePropertyMappings,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    raw: ProfileMappingApiRaw

    def __init__(self, api_client=None):
        super().__init__(api_client)
        self.raw = ProfileMappingApiRaw(api_client)
