# coding: utf-8

"""
    Okta API

    Allows customers to easily access the Okta API

    The version of the OpenAPI document: 2.16.0
    Contact: devex-public@okta.com
    Created by: https://developer.okta.com/
"""

from okta_python_sdk.paths.api_v1_roles_role_type_or_role_id_subscriptions_notification_type_unsubscribe.post import CustomRoleNotificationUnsubscribeRaw
from okta_python_sdk.paths.api_v1_roles_role_type_or_role_id_subscriptions_notification_type.get import GetRoleSubscriptionsByNotificationTypeRaw
from okta_python_sdk.paths.api_v1_roles_role_type_or_role_id_subscriptions.get import ListRoleSubscriptionsRaw
from okta_python_sdk.paths.api_v1_roles_role_type_or_role_id_subscriptions_notification_type_subscribe.post import RoleNotificationSubscribeRaw
from okta_python_sdk.paths.api_v1_users_user_id_subscriptions_notification_type_unsubscribe.post import UnsubscribeUserSubscriptionByNotificationTypeRaw
from okta_python_sdk.paths.api_v1_users_user_id_subscriptions_notification_type_subscribe.post import UserNotificationSubscribeRaw


class SubscriptionApiRaw(
    CustomRoleNotificationUnsubscribeRaw,
    GetRoleSubscriptionsByNotificationTypeRaw,
    ListRoleSubscriptionsRaw,
    RoleNotificationSubscribeRaw,
    UnsubscribeUserSubscriptionByNotificationTypeRaw,
    UserNotificationSubscribeRaw,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    pass
