# coding: utf-8

"""
    Okta API

    Allows customers to easily access the Okta API

    The version of the OpenAPI document: 2.16.0
    Contact: devex-public@okta.com
    Created by: https://developer.okta.com/
"""

from okta_python_sdk.paths.api_v1_templates_sms.post import AddNewCustomSmsRaw
from okta_python_sdk.paths.api_v1_templates_sms.get import EnumerateSmsTemplatesRaw
from okta_python_sdk.paths.api_v1_templates_sms_template_id.get import GetByIdRaw
from okta_python_sdk.paths.api_v1_templates_sms_template_id.post import PartialSmsUpdateRaw
from okta_python_sdk.paths.api_v1_templates_sms_template_id.delete import RemoveSmsRaw
from okta_python_sdk.paths.api_v1_templates_sms_template_id.put import UpdateSmsTemplateRaw


class TemplateApiRaw(
    AddNewCustomSmsRaw,
    EnumerateSmsTemplatesRaw,
    GetByIdRaw,
    PartialSmsUpdateRaw,
    RemoveSmsRaw,
    UpdateSmsTemplateRaw,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    pass
