# coding: utf-8

"""
    Okta API

    Allows customers to easily access the Okta API

    The version of the OpenAPI document: 2.16.0
    Contact: devex-public@okta.com
    Created by: https://developer.okta.com/
"""

from okta_python_sdk.paths.api_v1_meta_types_user.post import CreateNewUserType
from okta_python_sdk.paths.api_v1_meta_types_user_type_id.delete import DeletePermanently
from okta_python_sdk.paths.api_v1_meta_types_user.get import GetAllUserTypes
from okta_python_sdk.paths.api_v1_meta_types_user_type_id.get import GetById
from okta_python_sdk.paths.api_v1_meta_types_user_type_id.put import ReplaceExistingType
from okta_python_sdk.paths.api_v1_meta_types_user_type_id.post import UpdateExistingType
from okta_python_sdk.apis.tags.user_type_api_raw import UserTypeApiRaw


class UserTypeApi(
    CreateNewUserType,
    DeletePermanently,
    GetAllUserTypes,
    GetById,
    ReplaceExistingType,
    UpdateExistingType,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    raw: UserTypeApiRaw

    def __init__(self, api_client=None):
        super().__init__(api_client)
        self.raw = UserTypeApiRaw(api_client)
