# coding: utf-8

"""
    Okta API

    Allows customers to easily access the Okta API

    The version of the OpenAPI document: 2.16.0
    Contact: devex-public@okta.com
    Created by: https://developer.okta.com/
"""

from okta_python_sdk.paths.api_v1_users_user_id_factors_factor_id_lifecycle_activate.post import ActivateFactorLifecycleRaw
from okta_python_sdk.paths.api_v1_users_user_id_factors.post import EnrollSupportedFactorRaw
from okta_python_sdk.paths.api_v1_users_user_id_factors.get import EnumerateEnrolledRaw
from okta_python_sdk.paths.api_v1_users_user_id_factors_questions.get import EnumerateSecurityQuestionsRaw
from okta_python_sdk.paths.api_v1_users_user_id_factors_catalog.get import EnumerateSupportedFactorsRaw
from okta_python_sdk.paths.api_v1_users_user_id_factors_factor_id.get import GetFactorRaw
from okta_python_sdk.paths.api_v1_users_user_id_factors_factor_id_transactions_transaction_id.get import PollFactorTransactionStatusRaw
from okta_python_sdk.paths.api_v1_users_user_id_factors_factor_id.delete import UnenrollFactorRaw
from okta_python_sdk.paths.api_v1_users_user_id_factors_factor_id_verify.post import VerifyOtpRaw


class UserFactorApiRaw(
    ActivateFactorLifecycleRaw,
    EnrollSupportedFactorRaw,
    EnumerateEnrolledRaw,
    EnumerateSecurityQuestionsRaw,
    EnumerateSupportedFactorsRaw,
    GetFactorRaw,
    PollFactorTransactionStatusRaw,
    UnenrollFactorRaw,
    VerifyOtpRaw,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    pass
