# coding: utf-8

"""
    Okta API

    Allows customers to easily access the Okta API

    The version of the OpenAPI document: 2.16.0
    Contact: devex-public@okta.com
    Created by: https://developer.okta.com/
"""

from okta_python_sdk.paths.api_v1_users_user_id_factors_factor_id_lifecycle_activate.post import ActivateFactorLifecycle
from okta_python_sdk.paths.api_v1_users_user_id_factors.post import EnrollSupportedFactor
from okta_python_sdk.paths.api_v1_users_user_id_factors.get import EnumerateEnrolled
from okta_python_sdk.paths.api_v1_users_user_id_factors_questions.get import EnumerateSecurityQuestions
from okta_python_sdk.paths.api_v1_users_user_id_factors_catalog.get import EnumerateSupportedFactors
from okta_python_sdk.paths.api_v1_users_user_id_factors_factor_id.get import GetFactor
from okta_python_sdk.paths.api_v1_users_user_id_factors_factor_id_transactions_transaction_id.get import PollFactorTransactionStatus
from okta_python_sdk.paths.api_v1_users_user_id_factors_factor_id.delete import UnenrollFactor
from okta_python_sdk.paths.api_v1_users_user_id_factors_factor_id_verify.post import VerifyOtp
from okta_python_sdk.apis.tags.user_factor_api_raw import UserFactorApiRaw


class UserFactorApi(
    ActivateFactorLifecycle,
    EnrollSupportedFactor,
    EnumerateEnrolled,
    EnumerateSecurityQuestions,
    EnumerateSupportedFactors,
    GetFactor,
    PollFactorTransactionStatus,
    UnenrollFactor,
    VerifyOtp,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    raw: UserFactorApiRaw

    def __init__(self, api_client=None):
        super().__init__(api_client)
        self.raw = UserFactorApiRaw(api_client)
