import typing_extensions

from okta_python_sdk.paths import PathValues
from okta_python_sdk.apis.paths.api_v1_apps import ApiV1Apps
from okta_python_sdk.apis.paths.api_v1_apps_app_id import ApiV1AppsAppId
from okta_python_sdk.apis.paths.api_v1_apps_app_id_connections_default import ApiV1AppsAppIdConnectionsDefault
from okta_python_sdk.apis.paths.api_v1_apps_app_id_connections_default_lifecycle_activate import ApiV1AppsAppIdConnectionsDefaultLifecycleActivate
from okta_python_sdk.apis.paths.api_v1_apps_app_id_connections_default_lifecycle_deactivate import ApiV1AppsAppIdConnectionsDefaultLifecycleDeactivate
from okta_python_sdk.apis.paths.api_v1_apps_app_id_credentials_csrs import ApiV1AppsAppIdCredentialsCsrs
from okta_python_sdk.apis.paths.api_v1_apps_app_id_credentials_csrs_csr_id import ApiV1AppsAppIdCredentialsCsrsCsrId
from okta_python_sdk.apis.paths.api_v1_apps_app_id_credentials_csrs_csr_id_lifecycle_publish import ApiV1AppsAppIdCredentialsCsrsCsrIdLifecyclePublish
from okta_python_sdk.apis.paths.api_v1_apps_app_id_credentials_keys import ApiV1AppsAppIdCredentialsKeys
from okta_python_sdk.apis.paths.api_v1_apps_app_id_credentials_keys_generate import ApiV1AppsAppIdCredentialsKeysGenerate
from okta_python_sdk.apis.paths.api_v1_apps_app_id_credentials_keys_key_id import ApiV1AppsAppIdCredentialsKeysKeyId
from okta_python_sdk.apis.paths.api_v1_apps_app_id_credentials_keys_key_id_clone import ApiV1AppsAppIdCredentialsKeysKeyIdClone
from okta_python_sdk.apis.paths.api_v1_apps_app_id_credentials_secrets import ApiV1AppsAppIdCredentialsSecrets
from okta_python_sdk.apis.paths.api_v1_apps_app_id_credentials_secrets_secret_id import ApiV1AppsAppIdCredentialsSecretsSecretId
from okta_python_sdk.apis.paths.api_v1_apps_app_id_credentials_secrets_secret_id_lifecycle_activate import ApiV1AppsAppIdCredentialsSecretsSecretIdLifecycleActivate
from okta_python_sdk.apis.paths.api_v1_apps_app_id_credentials_secrets_secret_id_lifecycle_deactivate import ApiV1AppsAppIdCredentialsSecretsSecretIdLifecycleDeactivate
from okta_python_sdk.apis.paths.api_v1_apps_app_id_features import ApiV1AppsAppIdFeatures
from okta_python_sdk.apis.paths.api_v1_apps_app_id_features_name import ApiV1AppsAppIdFeaturesName
from okta_python_sdk.apis.paths.api_v1_apps_app_id_grants import ApiV1AppsAppIdGrants
from okta_python_sdk.apis.paths.api_v1_apps_app_id_grants_grant_id import ApiV1AppsAppIdGrantsGrantId
from okta_python_sdk.apis.paths.api_v1_apps_app_id_groups import ApiV1AppsAppIdGroups
from okta_python_sdk.apis.paths.api_v1_apps_app_id_groups_group_id import ApiV1AppsAppIdGroupsGroupId
from okta_python_sdk.apis.paths.api_v1_apps_app_id_lifecycle_activate import ApiV1AppsAppIdLifecycleActivate
from okta_python_sdk.apis.paths.api_v1_apps_app_id_lifecycle_deactivate import ApiV1AppsAppIdLifecycleDeactivate
from okta_python_sdk.apis.paths.api_v1_apps_app_id_logo import ApiV1AppsAppIdLogo
from okta_python_sdk.apis.paths.api_v1_apps_app_id_policies_policy_id import ApiV1AppsAppIdPoliciesPolicyId
from okta_python_sdk.apis.paths.api_v1_apps_app_id_sso_saml_metadata import ApiV1AppsAppIdSsoSamlMetadata
from okta_python_sdk.apis.paths.api_v1_apps_app_id_tokens import ApiV1AppsAppIdTokens
from okta_python_sdk.apis.paths.api_v1_apps_app_id_tokens_token_id import ApiV1AppsAppIdTokensTokenId
from okta_python_sdk.apis.paths.api_v1_apps_app_id_users import ApiV1AppsAppIdUsers
from okta_python_sdk.apis.paths.api_v1_apps_app_id_users_user_id import ApiV1AppsAppIdUsersUserId
from okta_python_sdk.apis.paths.api_v1_authenticators import ApiV1Authenticators
from okta_python_sdk.apis.paths.api_v1_authenticators_authenticator_id import ApiV1AuthenticatorsAuthenticatorId
from okta_python_sdk.apis.paths.api_v1_authenticators_authenticator_id_lifecycle_activate import ApiV1AuthenticatorsAuthenticatorIdLifecycleActivate
from okta_python_sdk.apis.paths.api_v1_authenticators_authenticator_id_lifecycle_deactivate import ApiV1AuthenticatorsAuthenticatorIdLifecycleDeactivate
from okta_python_sdk.apis.paths.api_v1_authorization_servers import ApiV1AuthorizationServers
from okta_python_sdk.apis.paths.api_v1_authorization_servers_auth_server_id import ApiV1AuthorizationServersAuthServerId
from okta_python_sdk.apis.paths.api_v1_authorization_servers_auth_server_id_claims import ApiV1AuthorizationServersAuthServerIdClaims
from okta_python_sdk.apis.paths.api_v1_authorization_servers_auth_server_id_claims_claim_id import ApiV1AuthorizationServersAuthServerIdClaimsClaimId
from okta_python_sdk.apis.paths.api_v1_authorization_servers_auth_server_id_clients import ApiV1AuthorizationServersAuthServerIdClients
from okta_python_sdk.apis.paths.api_v1_authorization_servers_auth_server_id_clients_client_id_tokens import ApiV1AuthorizationServersAuthServerIdClientsClientIdTokens
from okta_python_sdk.apis.paths.api_v1_authorization_servers_auth_server_id_clients_client_id_tokens_token_id import ApiV1AuthorizationServersAuthServerIdClientsClientIdTokensTokenId
from okta_python_sdk.apis.paths.api_v1_authorization_servers_auth_server_id_credentials_keys import ApiV1AuthorizationServersAuthServerIdCredentialsKeys
from okta_python_sdk.apis.paths.api_v1_authorization_servers_auth_server_id_credentials_lifecycle_key_rotate import ApiV1AuthorizationServersAuthServerIdCredentialsLifecycleKeyRotate
from okta_python_sdk.apis.paths.api_v1_authorization_servers_auth_server_id_lifecycle_activate import ApiV1AuthorizationServersAuthServerIdLifecycleActivate
from okta_python_sdk.apis.paths.api_v1_authorization_servers_auth_server_id_lifecycle_deactivate import ApiV1AuthorizationServersAuthServerIdLifecycleDeactivate
from okta_python_sdk.apis.paths.api_v1_authorization_servers_auth_server_id_policies import ApiV1AuthorizationServersAuthServerIdPolicies
from okta_python_sdk.apis.paths.api_v1_authorization_servers_auth_server_id_policies_policy_id import ApiV1AuthorizationServersAuthServerIdPoliciesPolicyId
from okta_python_sdk.apis.paths.api_v1_authorization_servers_auth_server_id_policies_policy_id_lifecycle_activate import ApiV1AuthorizationServersAuthServerIdPoliciesPolicyIdLifecycleActivate
from okta_python_sdk.apis.paths.api_v1_authorization_servers_auth_server_id_policies_policy_id_lifecycle_deactivate import ApiV1AuthorizationServersAuthServerIdPoliciesPolicyIdLifecycleDeactivate
from okta_python_sdk.apis.paths.api_v1_authorization_servers_auth_server_id_policies_policy_id_rules import ApiV1AuthorizationServersAuthServerIdPoliciesPolicyIdRules
from okta_python_sdk.apis.paths.api_v1_authorization_servers_auth_server_id_policies_policy_id_rules_rule_id import ApiV1AuthorizationServersAuthServerIdPoliciesPolicyIdRulesRuleId
from okta_python_sdk.apis.paths.api_v1_authorization_servers_auth_server_id_policies_policy_id_rules_rule_id_lifecycle_activate import ApiV1AuthorizationServersAuthServerIdPoliciesPolicyIdRulesRuleIdLifecycleActivate
from okta_python_sdk.apis.paths.api_v1_authorization_servers_auth_server_id_policies_policy_id_rules_rule_id_lifecycle_deactivate import ApiV1AuthorizationServersAuthServerIdPoliciesPolicyIdRulesRuleIdLifecycleDeactivate
from okta_python_sdk.apis.paths.api_v1_authorization_servers_auth_server_id_scopes import ApiV1AuthorizationServersAuthServerIdScopes
from okta_python_sdk.apis.paths.api_v1_authorization_servers_auth_server_id_scopes_scope_id import ApiV1AuthorizationServersAuthServerIdScopesScopeId
from okta_python_sdk.apis.paths.api_v1_brands import ApiV1Brands
from okta_python_sdk.apis.paths.api_v1_brands_brand_id import ApiV1BrandsBrandId
from okta_python_sdk.apis.paths.api_v1_brands_brand_id_templates_email import ApiV1BrandsBrandIdTemplatesEmail
from okta_python_sdk.apis.paths.api_v1_brands_brand_id_templates_email_template_name import ApiV1BrandsBrandIdTemplatesEmailTemplateName
from okta_python_sdk.apis.paths.api_v1_brands_brand_id_templates_email_template_name_customizations import ApiV1BrandsBrandIdTemplatesEmailTemplateNameCustomizations
from okta_python_sdk.apis.paths.api_v1_brands_brand_id_templates_email_template_name_customizations_customization_id import ApiV1BrandsBrandIdTemplatesEmailTemplateNameCustomizationsCustomizationId
from okta_python_sdk.apis.paths.api_v1_brands_brand_id_templates_email_template_name_customizations_customization_id_preview import ApiV1BrandsBrandIdTemplatesEmailTemplateNameCustomizationsCustomizationIdPreview
from okta_python_sdk.apis.paths.api_v1_brands_brand_id_templates_email_template_name_default_content import ApiV1BrandsBrandIdTemplatesEmailTemplateNameDefaultContent
from okta_python_sdk.apis.paths.api_v1_brands_brand_id_templates_email_template_name_default_content_preview import ApiV1BrandsBrandIdTemplatesEmailTemplateNameDefaultContentPreview
from okta_python_sdk.apis.paths.api_v1_brands_brand_id_templates_email_template_name_test import ApiV1BrandsBrandIdTemplatesEmailTemplateNameTest
from okta_python_sdk.apis.paths.api_v1_brands_brand_id_themes import ApiV1BrandsBrandIdThemes
from okta_python_sdk.apis.paths.api_v1_brands_brand_id_themes_theme_id import ApiV1BrandsBrandIdThemesThemeId
from okta_python_sdk.apis.paths.api_v1_brands_brand_id_themes_theme_id_background_image import ApiV1BrandsBrandIdThemesThemeIdBackgroundImage
from okta_python_sdk.apis.paths.api_v1_brands_brand_id_themes_theme_id_favicon import ApiV1BrandsBrandIdThemesThemeIdFavicon
from okta_python_sdk.apis.paths.api_v1_brands_brand_id_themes_theme_id_logo import ApiV1BrandsBrandIdThemesThemeIdLogo
from okta_python_sdk.apis.paths.api_v1_domains import ApiV1Domains
from okta_python_sdk.apis.paths.api_v1_domains_domain_id import ApiV1DomainsDomainId
from okta_python_sdk.apis.paths.api_v1_domains_domain_id_certificate import ApiV1DomainsDomainIdCertificate
from okta_python_sdk.apis.paths.api_v1_domains_domain_id_verify import ApiV1DomainsDomainIdVerify
from okta_python_sdk.apis.paths.api_v1_event_hooks import ApiV1EventHooks
from okta_python_sdk.apis.paths.api_v1_event_hooks_event_hook_id import ApiV1EventHooksEventHookId
from okta_python_sdk.apis.paths.api_v1_event_hooks_event_hook_id_lifecycle_activate import ApiV1EventHooksEventHookIdLifecycleActivate
from okta_python_sdk.apis.paths.api_v1_event_hooks_event_hook_id_lifecycle_deactivate import ApiV1EventHooksEventHookIdLifecycleDeactivate
from okta_python_sdk.apis.paths.api_v1_event_hooks_event_hook_id_lifecycle_verify import ApiV1EventHooksEventHookIdLifecycleVerify
from okta_python_sdk.apis.paths.api_v1_features import ApiV1Features
from okta_python_sdk.apis.paths.api_v1_features_feature_id import ApiV1FeaturesFeatureId
from okta_python_sdk.apis.paths.api_v1_features_feature_id_dependencies import ApiV1FeaturesFeatureIdDependencies
from okta_python_sdk.apis.paths.api_v1_features_feature_id_dependents import ApiV1FeaturesFeatureIdDependents
from okta_python_sdk.apis.paths.api_v1_features_feature_id_lifecycle import ApiV1FeaturesFeatureIdLifecycle
from okta_python_sdk.apis.paths.api_v1_groups import ApiV1Groups
from okta_python_sdk.apis.paths.api_v1_groups_rules import ApiV1GroupsRules
from okta_python_sdk.apis.paths.api_v1_groups_rules_rule_id import ApiV1GroupsRulesRuleId
from okta_python_sdk.apis.paths.api_v1_groups_rules_rule_id_lifecycle_activate import ApiV1GroupsRulesRuleIdLifecycleActivate
from okta_python_sdk.apis.paths.api_v1_groups_rules_rule_id_lifecycle_deactivate import ApiV1GroupsRulesRuleIdLifecycleDeactivate
from okta_python_sdk.apis.paths.api_v1_groups_group_id import ApiV1GroupsGroupId
from okta_python_sdk.apis.paths.api_v1_groups_group_id_apps import ApiV1GroupsGroupIdApps
from okta_python_sdk.apis.paths.api_v1_groups_group_id_roles import ApiV1GroupsGroupIdRoles
from okta_python_sdk.apis.paths.api_v1_groups_group_id_roles_role_id import ApiV1GroupsGroupIdRolesRoleId
from okta_python_sdk.apis.paths.api_v1_groups_group_id_roles_role_id_targets_catalog_apps import ApiV1GroupsGroupIdRolesRoleIdTargetsCatalogApps
from okta_python_sdk.apis.paths.api_v1_groups_group_id_roles_role_id_targets_catalog_apps_app_name import ApiV1GroupsGroupIdRolesRoleIdTargetsCatalogAppsAppName
from okta_python_sdk.apis.paths.api_v1_groups_group_id_roles_role_id_targets_catalog_apps_app_name_application_id import ApiV1GroupsGroupIdRolesRoleIdTargetsCatalogAppsAppNameApplicationId
from okta_python_sdk.apis.paths.api_v1_groups_group_id_roles_role_id_targets_groups import ApiV1GroupsGroupIdRolesRoleIdTargetsGroups
from okta_python_sdk.apis.paths.api_v1_groups_group_id_roles_role_id_targets_groups_target_group_id import ApiV1GroupsGroupIdRolesRoleIdTargetsGroupsTargetGroupId
from okta_python_sdk.apis.paths.api_v1_groups_group_id_users import ApiV1GroupsGroupIdUsers
from okta_python_sdk.apis.paths.api_v1_groups_group_id_users_user_id import ApiV1GroupsGroupIdUsersUserId
from okta_python_sdk.apis.paths.api_v1_idps import ApiV1Idps
from okta_python_sdk.apis.paths.api_v1_idps_credentials_keys import ApiV1IdpsCredentialsKeys
from okta_python_sdk.apis.paths.api_v1_idps_credentials_keys_key_id import ApiV1IdpsCredentialsKeysKeyId
from okta_python_sdk.apis.paths.api_v1_idps_idp_id import ApiV1IdpsIdpId
from okta_python_sdk.apis.paths.api_v1_idps_idp_id_credentials_csrs import ApiV1IdpsIdpIdCredentialsCsrs
from okta_python_sdk.apis.paths.api_v1_idps_idp_id_credentials_csrs_csr_id import ApiV1IdpsIdpIdCredentialsCsrsCsrId
from okta_python_sdk.apis.paths.api_v1_idps_idp_id_credentials_csrs_csr_id_lifecycle_publish import ApiV1IdpsIdpIdCredentialsCsrsCsrIdLifecyclePublish
from okta_python_sdk.apis.paths.api_v1_idps_idp_id_credentials_keys import ApiV1IdpsIdpIdCredentialsKeys
from okta_python_sdk.apis.paths.api_v1_idps_idp_id_credentials_keys_generate import ApiV1IdpsIdpIdCredentialsKeysGenerate
from okta_python_sdk.apis.paths.api_v1_idps_idp_id_credentials_keys_key_id import ApiV1IdpsIdpIdCredentialsKeysKeyId
from okta_python_sdk.apis.paths.api_v1_idps_idp_id_credentials_keys_key_id_clone import ApiV1IdpsIdpIdCredentialsKeysKeyIdClone
from okta_python_sdk.apis.paths.api_v1_idps_idp_id_lifecycle_activate import ApiV1IdpsIdpIdLifecycleActivate
from okta_python_sdk.apis.paths.api_v1_idps_idp_id_lifecycle_deactivate import ApiV1IdpsIdpIdLifecycleDeactivate
from okta_python_sdk.apis.paths.api_v1_idps_idp_id_users import ApiV1IdpsIdpIdUsers
from okta_python_sdk.apis.paths.api_v1_idps_idp_id_users_user_id import ApiV1IdpsIdpIdUsersUserId
from okta_python_sdk.apis.paths.api_v1_idps_idp_id_users_user_id_credentials_tokens import ApiV1IdpsIdpIdUsersUserIdCredentialsTokens
from okta_python_sdk.apis.paths.api_v1_inline_hooks import ApiV1InlineHooks
from okta_python_sdk.apis.paths.api_v1_inline_hooks_inline_hook_id import ApiV1InlineHooksInlineHookId
from okta_python_sdk.apis.paths.api_v1_inline_hooks_inline_hook_id_execute import ApiV1InlineHooksInlineHookIdExecute
from okta_python_sdk.apis.paths.api_v1_inline_hooks_inline_hook_id_lifecycle_activate import ApiV1InlineHooksInlineHookIdLifecycleActivate
from okta_python_sdk.apis.paths.api_v1_inline_hooks_inline_hook_id_lifecycle_deactivate import ApiV1InlineHooksInlineHookIdLifecycleDeactivate
from okta_python_sdk.apis.paths.api_v1_logs import ApiV1Logs
from okta_python_sdk.apis.paths.api_v1_mappings import ApiV1Mappings
from okta_python_sdk.apis.paths.api_v1_mappings_mapping_id import ApiV1MappingsMappingId
from okta_python_sdk.apis.paths.api_v1_meta_schemas_apps_app_instance_id_default import ApiV1MetaSchemasAppsAppInstanceIdDefault
from okta_python_sdk.apis.paths.api_v1_meta_schemas_group_default import ApiV1MetaSchemasGroupDefault
from okta_python_sdk.apis.paths.api_v1_meta_schemas_user_linked_objects import ApiV1MetaSchemasUserLinkedObjects
from okta_python_sdk.apis.paths.api_v1_meta_schemas_user_linked_objects_linked_object_name import ApiV1MetaSchemasUserLinkedObjectsLinkedObjectName
from okta_python_sdk.apis.paths.api_v1_meta_schemas_user_schema_id import ApiV1MetaSchemasUserSchemaId
from okta_python_sdk.apis.paths.api_v1_meta_types_user import ApiV1MetaTypesUser
from okta_python_sdk.apis.paths.api_v1_meta_types_user_type_id import ApiV1MetaTypesUserTypeId
from okta_python_sdk.apis.paths.api_v1_org import ApiV1Org
from okta_python_sdk.apis.paths.api_v1_org_contacts import ApiV1OrgContacts
from okta_python_sdk.apis.paths.api_v1_org_contacts_contact_type import ApiV1OrgContactsContactType
from okta_python_sdk.apis.paths.api_v1_org_logo import ApiV1OrgLogo
from okta_python_sdk.apis.paths.api_v1_org_preferences import ApiV1OrgPreferences
from okta_python_sdk.apis.paths.api_v1_org_preferences_hide_end_user_footer import ApiV1OrgPreferencesHideEndUserFooter
from okta_python_sdk.apis.paths.api_v1_org_preferences_show_end_user_footer import ApiV1OrgPreferencesShowEndUserFooter
from okta_python_sdk.apis.paths.api_v1_org_privacy_okta_communication import ApiV1OrgPrivacyOktaCommunication
from okta_python_sdk.apis.paths.api_v1_org_privacy_okta_communication_opt_in import ApiV1OrgPrivacyOktaCommunicationOptIn
from okta_python_sdk.apis.paths.api_v1_org_privacy_okta_communication_opt_out import ApiV1OrgPrivacyOktaCommunicationOptOut
from okta_python_sdk.apis.paths.api_v1_org_privacy_okta_support import ApiV1OrgPrivacyOktaSupport
from okta_python_sdk.apis.paths.api_v1_org_privacy_okta_support_extend import ApiV1OrgPrivacyOktaSupportExtend
from okta_python_sdk.apis.paths.api_v1_org_privacy_okta_support_grant import ApiV1OrgPrivacyOktaSupportGrant
from okta_python_sdk.apis.paths.api_v1_org_privacy_okta_support_revoke import ApiV1OrgPrivacyOktaSupportRevoke
from okta_python_sdk.apis.paths.api_v1_policies import ApiV1Policies
from okta_python_sdk.apis.paths.api_v1_policies_policy_id import ApiV1PoliciesPolicyId
from okta_python_sdk.apis.paths.api_v1_policies_policy_id_lifecycle_activate import ApiV1PoliciesPolicyIdLifecycleActivate
from okta_python_sdk.apis.paths.api_v1_policies_policy_id_lifecycle_deactivate import ApiV1PoliciesPolicyIdLifecycleDeactivate
from okta_python_sdk.apis.paths.api_v1_policies_policy_id_rules import ApiV1PoliciesPolicyIdRules
from okta_python_sdk.apis.paths.api_v1_policies_policy_id_rules_rule_id import ApiV1PoliciesPolicyIdRulesRuleId
from okta_python_sdk.apis.paths.api_v1_policies_policy_id_rules_rule_id_lifecycle_activate import ApiV1PoliciesPolicyIdRulesRuleIdLifecycleActivate
from okta_python_sdk.apis.paths.api_v1_policies_policy_id_rules_rule_id_lifecycle_deactivate import ApiV1PoliciesPolicyIdRulesRuleIdLifecycleDeactivate
from okta_python_sdk.apis.paths.api_v1_roles_role_type_or_role_id_subscriptions import ApiV1RolesRoleTypeOrRoleIdSubscriptions
from okta_python_sdk.apis.paths.api_v1_roles_role_type_or_role_id_subscriptions_notification_type import ApiV1RolesRoleTypeOrRoleIdSubscriptionsNotificationType
from okta_python_sdk.apis.paths.api_v1_roles_role_type_or_role_id_subscriptions_notification_type_subscribe import ApiV1RolesRoleTypeOrRoleIdSubscriptionsNotificationTypeSubscribe
from okta_python_sdk.apis.paths.api_v1_roles_role_type_or_role_id_subscriptions_notification_type_unsubscribe import ApiV1RolesRoleTypeOrRoleIdSubscriptionsNotificationTypeUnsubscribe
from okta_python_sdk.apis.paths.api_v1_sessions import ApiV1Sessions
from okta_python_sdk.apis.paths.api_v1_sessions_session_id import ApiV1SessionsSessionId
from okta_python_sdk.apis.paths.api_v1_sessions_session_id_lifecycle_refresh import ApiV1SessionsSessionIdLifecycleRefresh
from okta_python_sdk.apis.paths.api_v1_templates_sms import ApiV1TemplatesSms
from okta_python_sdk.apis.paths.api_v1_templates_sms_template_id import ApiV1TemplatesSmsTemplateId
from okta_python_sdk.apis.paths.api_v1_threats_configuration import ApiV1ThreatsConfiguration
from okta_python_sdk.apis.paths.api_v1_trusted_origins import ApiV1TrustedOrigins
from okta_python_sdk.apis.paths.api_v1_trusted_origins_trusted_origin_id import ApiV1TrustedOriginsTrustedOriginId
from okta_python_sdk.apis.paths.api_v1_trusted_origins_trusted_origin_id_lifecycle_activate import ApiV1TrustedOriginsTrustedOriginIdLifecycleActivate
from okta_python_sdk.apis.paths.api_v1_trusted_origins_trusted_origin_id_lifecycle_deactivate import ApiV1TrustedOriginsTrustedOriginIdLifecycleDeactivate
from okta_python_sdk.apis.paths.api_v1_users import ApiV1Users
from okta_python_sdk.apis.paths.api_v1_users_associated_user_id_linked_objects_primary_relationship_name_primary_user_id import ApiV1UsersAssociatedUserIdLinkedObjectsPrimaryRelationshipNamePrimaryUserId
from okta_python_sdk.apis.paths.api_v1_users_user_id import ApiV1UsersUserId
from okta_python_sdk.apis.paths.api_v1_users_user_id_app_links import ApiV1UsersUserIdAppLinks
from okta_python_sdk.apis.paths.api_v1_users_user_id_clients import ApiV1UsersUserIdClients
from okta_python_sdk.apis.paths.api_v1_users_user_id_clients_client_id_grants import ApiV1UsersUserIdClientsClientIdGrants
from okta_python_sdk.apis.paths.api_v1_users_user_id_clients_client_id_tokens import ApiV1UsersUserIdClientsClientIdTokens
from okta_python_sdk.apis.paths.api_v1_users_user_id_clients_client_id_tokens_token_id import ApiV1UsersUserIdClientsClientIdTokensTokenId
from okta_python_sdk.apis.paths.api_v1_users_user_id_credentials_change_password import ApiV1UsersUserIdCredentialsChangePassword
from okta_python_sdk.apis.paths.api_v1_users_user_id_credentials_change_recovery_question import ApiV1UsersUserIdCredentialsChangeRecoveryQuestion
from okta_python_sdk.apis.paths.api_v1_users_user_id_credentials_forgot_password import ApiV1UsersUserIdCredentialsForgotPassword
from okta_python_sdk.apis.paths.api_v1_users_user_id_factors import ApiV1UsersUserIdFactors
from okta_python_sdk.apis.paths.api_v1_users_user_id_factors_catalog import ApiV1UsersUserIdFactorsCatalog
from okta_python_sdk.apis.paths.api_v1_users_user_id_factors_questions import ApiV1UsersUserIdFactorsQuestions
from okta_python_sdk.apis.paths.api_v1_users_user_id_factors_factor_id import ApiV1UsersUserIdFactorsFactorId
from okta_python_sdk.apis.paths.api_v1_users_user_id_factors_factor_id_lifecycle_activate import ApiV1UsersUserIdFactorsFactorIdLifecycleActivate
from okta_python_sdk.apis.paths.api_v1_users_user_id_factors_factor_id_transactions_transaction_id import ApiV1UsersUserIdFactorsFactorIdTransactionsTransactionId
from okta_python_sdk.apis.paths.api_v1_users_user_id_factors_factor_id_verify import ApiV1UsersUserIdFactorsFactorIdVerify
from okta_python_sdk.apis.paths.api_v1_users_user_id_grants import ApiV1UsersUserIdGrants
from okta_python_sdk.apis.paths.api_v1_users_user_id_grants_grant_id import ApiV1UsersUserIdGrantsGrantId
from okta_python_sdk.apis.paths.api_v1_users_user_id_groups import ApiV1UsersUserIdGroups
from okta_python_sdk.apis.paths.api_v1_users_user_id_idps import ApiV1UsersUserIdIdps
from okta_python_sdk.apis.paths.api_v1_users_user_id_lifecycle_activate import ApiV1UsersUserIdLifecycleActivate
from okta_python_sdk.apis.paths.api_v1_users_user_id_lifecycle_deactivate import ApiV1UsersUserIdLifecycleDeactivate
from okta_python_sdk.apis.paths.api_v1_users_user_id_lifecycle_expire_passwordtemp_passwordfalse import ApiV1UsersUserIdLifecycleExpirePasswordtempPasswordfalse
from okta_python_sdk.apis.paths.api_v1_users_user_id_lifecycle_expire_passwordtemp_passwordtrue import ApiV1UsersUserIdLifecycleExpirePasswordtempPasswordtrue
from okta_python_sdk.apis.paths.api_v1_users_user_id_lifecycle_reactivate import ApiV1UsersUserIdLifecycleReactivate
from okta_python_sdk.apis.paths.api_v1_users_user_id_lifecycle_reset_factors import ApiV1UsersUserIdLifecycleResetFactors
from okta_python_sdk.apis.paths.api_v1_users_user_id_lifecycle_reset_password import ApiV1UsersUserIdLifecycleResetPassword
from okta_python_sdk.apis.paths.api_v1_users_user_id_lifecycle_suspend import ApiV1UsersUserIdLifecycleSuspend
from okta_python_sdk.apis.paths.api_v1_users_user_id_lifecycle_unlock import ApiV1UsersUserIdLifecycleUnlock
from okta_python_sdk.apis.paths.api_v1_users_user_id_lifecycle_unsuspend import ApiV1UsersUserIdLifecycleUnsuspend
from okta_python_sdk.apis.paths.api_v1_users_user_id_linked_objects_relationship_name import ApiV1UsersUserIdLinkedObjectsRelationshipName
from okta_python_sdk.apis.paths.api_v1_users_user_id_roles import ApiV1UsersUserIdRoles
from okta_python_sdk.apis.paths.api_v1_users_user_id_roles_role_id import ApiV1UsersUserIdRolesRoleId
from okta_python_sdk.apis.paths.api_v1_users_user_id_roles_role_id_targets_catalog_apps import ApiV1UsersUserIdRolesRoleIdTargetsCatalogApps
from okta_python_sdk.apis.paths.api_v1_users_user_id_roles_role_id_targets_catalog_apps_app_name import ApiV1UsersUserIdRolesRoleIdTargetsCatalogAppsAppName
from okta_python_sdk.apis.paths.api_v1_users_user_id_roles_role_id_targets_catalog_apps_app_name_application_id import ApiV1UsersUserIdRolesRoleIdTargetsCatalogAppsAppNameApplicationId
from okta_python_sdk.apis.paths.api_v1_users_user_id_roles_role_id_targets_groups import ApiV1UsersUserIdRolesRoleIdTargetsGroups
from okta_python_sdk.apis.paths.api_v1_users_user_id_roles_role_id_targets_groups_group_id import ApiV1UsersUserIdRolesRoleIdTargetsGroupsGroupId
from okta_python_sdk.apis.paths.api_v1_users_user_id_sessions import ApiV1UsersUserIdSessions
from okta_python_sdk.apis.paths.api_v1_users_user_id_subscriptions import ApiV1UsersUserIdSubscriptions
from okta_python_sdk.apis.paths.api_v1_users_user_id_subscriptions_notification_type import ApiV1UsersUserIdSubscriptionsNotificationType
from okta_python_sdk.apis.paths.api_v1_users_user_id_subscriptions_notification_type_subscribe import ApiV1UsersUserIdSubscriptionsNotificationTypeSubscribe
from okta_python_sdk.apis.paths.api_v1_users_user_id_subscriptions_notification_type_unsubscribe import ApiV1UsersUserIdSubscriptionsNotificationTypeUnsubscribe
from okta_python_sdk.apis.paths.api_v1_zones import ApiV1Zones
from okta_python_sdk.apis.paths.api_v1_zones_zone_id import ApiV1ZonesZoneId
from okta_python_sdk.apis.paths.api_v1_zones_zone_id_lifecycle_activate import ApiV1ZonesZoneIdLifecycleActivate
from okta_python_sdk.apis.paths.api_v1_zones_zone_id_lifecycle_deactivate import ApiV1ZonesZoneIdLifecycleDeactivate

PathToApi = typing_extensions.TypedDict(
    'PathToApi',
    {
        PathValues.API_V1_APPS: ApiV1Apps,
        PathValues.API_V1_APPS_APP_ID: ApiV1AppsAppId,
        PathValues.API_V1_APPS_APP_ID_CONNECTIONS_DEFAULT: ApiV1AppsAppIdConnectionsDefault,
        PathValues.API_V1_APPS_APP_ID_CONNECTIONS_DEFAULT_LIFECYCLE_ACTIVATE: ApiV1AppsAppIdConnectionsDefaultLifecycleActivate,
        PathValues.API_V1_APPS_APP_ID_CONNECTIONS_DEFAULT_LIFECYCLE_DEACTIVATE: ApiV1AppsAppIdConnectionsDefaultLifecycleDeactivate,
        PathValues.API_V1_APPS_APP_ID_CREDENTIALS_CSRS: ApiV1AppsAppIdCredentialsCsrs,
        PathValues.API_V1_APPS_APP_ID_CREDENTIALS_CSRS_CSR_ID: ApiV1AppsAppIdCredentialsCsrsCsrId,
        PathValues.API_V1_APPS_APP_ID_CREDENTIALS_CSRS_CSR_ID_LIFECYCLE_PUBLISH: ApiV1AppsAppIdCredentialsCsrsCsrIdLifecyclePublish,
        PathValues.API_V1_APPS_APP_ID_CREDENTIALS_KEYS: ApiV1AppsAppIdCredentialsKeys,
        PathValues.API_V1_APPS_APP_ID_CREDENTIALS_KEYS_GENERATE: ApiV1AppsAppIdCredentialsKeysGenerate,
        PathValues.API_V1_APPS_APP_ID_CREDENTIALS_KEYS_KEY_ID: ApiV1AppsAppIdCredentialsKeysKeyId,
        PathValues.API_V1_APPS_APP_ID_CREDENTIALS_KEYS_KEY_ID_CLONE: ApiV1AppsAppIdCredentialsKeysKeyIdClone,
        PathValues.API_V1_APPS_APP_ID_CREDENTIALS_SECRETS: ApiV1AppsAppIdCredentialsSecrets,
        PathValues.API_V1_APPS_APP_ID_CREDENTIALS_SECRETS_SECRET_ID: ApiV1AppsAppIdCredentialsSecretsSecretId,
        PathValues.API_V1_APPS_APP_ID_CREDENTIALS_SECRETS_SECRET_ID_LIFECYCLE_ACTIVATE: ApiV1AppsAppIdCredentialsSecretsSecretIdLifecycleActivate,
        PathValues.API_V1_APPS_APP_ID_CREDENTIALS_SECRETS_SECRET_ID_LIFECYCLE_DEACTIVATE: ApiV1AppsAppIdCredentialsSecretsSecretIdLifecycleDeactivate,
        PathValues.API_V1_APPS_APP_ID_FEATURES: ApiV1AppsAppIdFeatures,
        PathValues.API_V1_APPS_APP_ID_FEATURES_NAME: ApiV1AppsAppIdFeaturesName,
        PathValues.API_V1_APPS_APP_ID_GRANTS: ApiV1AppsAppIdGrants,
        PathValues.API_V1_APPS_APP_ID_GRANTS_GRANT_ID: ApiV1AppsAppIdGrantsGrantId,
        PathValues.API_V1_APPS_APP_ID_GROUPS: ApiV1AppsAppIdGroups,
        PathValues.API_V1_APPS_APP_ID_GROUPS_GROUP_ID: ApiV1AppsAppIdGroupsGroupId,
        PathValues.API_V1_APPS_APP_ID_LIFECYCLE_ACTIVATE: ApiV1AppsAppIdLifecycleActivate,
        PathValues.API_V1_APPS_APP_ID_LIFECYCLE_DEACTIVATE: ApiV1AppsAppIdLifecycleDeactivate,
        PathValues.API_V1_APPS_APP_ID_LOGO: ApiV1AppsAppIdLogo,
        PathValues.API_V1_APPS_APP_ID_POLICIES_POLICY_ID: ApiV1AppsAppIdPoliciesPolicyId,
        PathValues.API_V1_APPS_APP_ID_SSO_SAML_METADATA: ApiV1AppsAppIdSsoSamlMetadata,
        PathValues.API_V1_APPS_APP_ID_TOKENS: ApiV1AppsAppIdTokens,
        PathValues.API_V1_APPS_APP_ID_TOKENS_TOKEN_ID: ApiV1AppsAppIdTokensTokenId,
        PathValues.API_V1_APPS_APP_ID_USERS: ApiV1AppsAppIdUsers,
        PathValues.API_V1_APPS_APP_ID_USERS_USER_ID: ApiV1AppsAppIdUsersUserId,
        PathValues.API_V1_AUTHENTICATORS: ApiV1Authenticators,
        PathValues.API_V1_AUTHENTICATORS_AUTHENTICATOR_ID: ApiV1AuthenticatorsAuthenticatorId,
        PathValues.API_V1_AUTHENTICATORS_AUTHENTICATOR_ID_LIFECYCLE_ACTIVATE: ApiV1AuthenticatorsAuthenticatorIdLifecycleActivate,
        PathValues.API_V1_AUTHENTICATORS_AUTHENTICATOR_ID_LIFECYCLE_DEACTIVATE: ApiV1AuthenticatorsAuthenticatorIdLifecycleDeactivate,
        PathValues.API_V1_AUTHORIZATION_SERVERS: ApiV1AuthorizationServers,
        PathValues.API_V1_AUTHORIZATION_SERVERS_AUTH_SERVER_ID: ApiV1AuthorizationServersAuthServerId,
        PathValues.API_V1_AUTHORIZATION_SERVERS_AUTH_SERVER_ID_CLAIMS: ApiV1AuthorizationServersAuthServerIdClaims,
        PathValues.API_V1_AUTHORIZATION_SERVERS_AUTH_SERVER_ID_CLAIMS_CLAIM_ID: ApiV1AuthorizationServersAuthServerIdClaimsClaimId,
        PathValues.API_V1_AUTHORIZATION_SERVERS_AUTH_SERVER_ID_CLIENTS: ApiV1AuthorizationServersAuthServerIdClients,
        PathValues.API_V1_AUTHORIZATION_SERVERS_AUTH_SERVER_ID_CLIENTS_CLIENT_ID_TOKENS: ApiV1AuthorizationServersAuthServerIdClientsClientIdTokens,
        PathValues.API_V1_AUTHORIZATION_SERVERS_AUTH_SERVER_ID_CLIENTS_CLIENT_ID_TOKENS_TOKEN_ID: ApiV1AuthorizationServersAuthServerIdClientsClientIdTokensTokenId,
        PathValues.API_V1_AUTHORIZATION_SERVERS_AUTH_SERVER_ID_CREDENTIALS_KEYS: ApiV1AuthorizationServersAuthServerIdCredentialsKeys,
        PathValues.API_V1_AUTHORIZATION_SERVERS_AUTH_SERVER_ID_CREDENTIALS_LIFECYCLE_KEY_ROTATE: ApiV1AuthorizationServersAuthServerIdCredentialsLifecycleKeyRotate,
        PathValues.API_V1_AUTHORIZATION_SERVERS_AUTH_SERVER_ID_LIFECYCLE_ACTIVATE: ApiV1AuthorizationServersAuthServerIdLifecycleActivate,
        PathValues.API_V1_AUTHORIZATION_SERVERS_AUTH_SERVER_ID_LIFECYCLE_DEACTIVATE: ApiV1AuthorizationServersAuthServerIdLifecycleDeactivate,
        PathValues.API_V1_AUTHORIZATION_SERVERS_AUTH_SERVER_ID_POLICIES: ApiV1AuthorizationServersAuthServerIdPolicies,
        PathValues.API_V1_AUTHORIZATION_SERVERS_AUTH_SERVER_ID_POLICIES_POLICY_ID: ApiV1AuthorizationServersAuthServerIdPoliciesPolicyId,
        PathValues.API_V1_AUTHORIZATION_SERVERS_AUTH_SERVER_ID_POLICIES_POLICY_ID_LIFECYCLE_ACTIVATE: ApiV1AuthorizationServersAuthServerIdPoliciesPolicyIdLifecycleActivate,
        PathValues.API_V1_AUTHORIZATION_SERVERS_AUTH_SERVER_ID_POLICIES_POLICY_ID_LIFECYCLE_DEACTIVATE: ApiV1AuthorizationServersAuthServerIdPoliciesPolicyIdLifecycleDeactivate,
        PathValues.API_V1_AUTHORIZATION_SERVERS_AUTH_SERVER_ID_POLICIES_POLICY_ID_RULES: ApiV1AuthorizationServersAuthServerIdPoliciesPolicyIdRules,
        PathValues.API_V1_AUTHORIZATION_SERVERS_AUTH_SERVER_ID_POLICIES_POLICY_ID_RULES_RULE_ID: ApiV1AuthorizationServersAuthServerIdPoliciesPolicyIdRulesRuleId,
        PathValues.API_V1_AUTHORIZATION_SERVERS_AUTH_SERVER_ID_POLICIES_POLICY_ID_RULES_RULE_ID_LIFECYCLE_ACTIVATE: ApiV1AuthorizationServersAuthServerIdPoliciesPolicyIdRulesRuleIdLifecycleActivate,
        PathValues.API_V1_AUTHORIZATION_SERVERS_AUTH_SERVER_ID_POLICIES_POLICY_ID_RULES_RULE_ID_LIFECYCLE_DEACTIVATE: ApiV1AuthorizationServersAuthServerIdPoliciesPolicyIdRulesRuleIdLifecycleDeactivate,
        PathValues.API_V1_AUTHORIZATION_SERVERS_AUTH_SERVER_ID_SCOPES: ApiV1AuthorizationServersAuthServerIdScopes,
        PathValues.API_V1_AUTHORIZATION_SERVERS_AUTH_SERVER_ID_SCOPES_SCOPE_ID: ApiV1AuthorizationServersAuthServerIdScopesScopeId,
        PathValues.API_V1_BRANDS: ApiV1Brands,
        PathValues.API_V1_BRANDS_BRAND_ID: ApiV1BrandsBrandId,
        PathValues.API_V1_BRANDS_BRAND_ID_TEMPLATES_EMAIL: ApiV1BrandsBrandIdTemplatesEmail,
        PathValues.API_V1_BRANDS_BRAND_ID_TEMPLATES_EMAIL_TEMPLATE_NAME: ApiV1BrandsBrandIdTemplatesEmailTemplateName,
        PathValues.API_V1_BRANDS_BRAND_ID_TEMPLATES_EMAIL_TEMPLATE_NAME_CUSTOMIZATIONS: ApiV1BrandsBrandIdTemplatesEmailTemplateNameCustomizations,
        PathValues.API_V1_BRANDS_BRAND_ID_TEMPLATES_EMAIL_TEMPLATE_NAME_CUSTOMIZATIONS_CUSTOMIZATION_ID: ApiV1BrandsBrandIdTemplatesEmailTemplateNameCustomizationsCustomizationId,
        PathValues.API_V1_BRANDS_BRAND_ID_TEMPLATES_EMAIL_TEMPLATE_NAME_CUSTOMIZATIONS_CUSTOMIZATION_ID_PREVIEW: ApiV1BrandsBrandIdTemplatesEmailTemplateNameCustomizationsCustomizationIdPreview,
        PathValues.API_V1_BRANDS_BRAND_ID_TEMPLATES_EMAIL_TEMPLATE_NAME_DEFAULTCONTENT: ApiV1BrandsBrandIdTemplatesEmailTemplateNameDefaultContent,
        PathValues.API_V1_BRANDS_BRAND_ID_TEMPLATES_EMAIL_TEMPLATE_NAME_DEFAULTCONTENT_PREVIEW: ApiV1BrandsBrandIdTemplatesEmailTemplateNameDefaultContentPreview,
        PathValues.API_V1_BRANDS_BRAND_ID_TEMPLATES_EMAIL_TEMPLATE_NAME_TEST: ApiV1BrandsBrandIdTemplatesEmailTemplateNameTest,
        PathValues.API_V1_BRANDS_BRAND_ID_THEMES: ApiV1BrandsBrandIdThemes,
        PathValues.API_V1_BRANDS_BRAND_ID_THEMES_THEME_ID: ApiV1BrandsBrandIdThemesThemeId,
        PathValues.API_V1_BRANDS_BRAND_ID_THEMES_THEME_ID_BACKGROUNDIMAGE: ApiV1BrandsBrandIdThemesThemeIdBackgroundImage,
        PathValues.API_V1_BRANDS_BRAND_ID_THEMES_THEME_ID_FAVICON: ApiV1BrandsBrandIdThemesThemeIdFavicon,
        PathValues.API_V1_BRANDS_BRAND_ID_THEMES_THEME_ID_LOGO: ApiV1BrandsBrandIdThemesThemeIdLogo,
        PathValues.API_V1_DOMAINS: ApiV1Domains,
        PathValues.API_V1_DOMAINS_DOMAIN_ID: ApiV1DomainsDomainId,
        PathValues.API_V1_DOMAINS_DOMAIN_ID_CERTIFICATE: ApiV1DomainsDomainIdCertificate,
        PathValues.API_V1_DOMAINS_DOMAIN_ID_VERIFY: ApiV1DomainsDomainIdVerify,
        PathValues.API_V1_EVENT_HOOKS: ApiV1EventHooks,
        PathValues.API_V1_EVENT_HOOKS_EVENT_HOOK_ID: ApiV1EventHooksEventHookId,
        PathValues.API_V1_EVENT_HOOKS_EVENT_HOOK_ID_LIFECYCLE_ACTIVATE: ApiV1EventHooksEventHookIdLifecycleActivate,
        PathValues.API_V1_EVENT_HOOKS_EVENT_HOOK_ID_LIFECYCLE_DEACTIVATE: ApiV1EventHooksEventHookIdLifecycleDeactivate,
        PathValues.API_V1_EVENT_HOOKS_EVENT_HOOK_ID_LIFECYCLE_VERIFY: ApiV1EventHooksEventHookIdLifecycleVerify,
        PathValues.API_V1_FEATURES: ApiV1Features,
        PathValues.API_V1_FEATURES_FEATURE_ID: ApiV1FeaturesFeatureId,
        PathValues.API_V1_FEATURES_FEATURE_ID_DEPENDENCIES: ApiV1FeaturesFeatureIdDependencies,
        PathValues.API_V1_FEATURES_FEATURE_ID_DEPENDENTS: ApiV1FeaturesFeatureIdDependents,
        PathValues.API_V1_FEATURES_FEATURE_ID_LIFECYCLE: ApiV1FeaturesFeatureIdLifecycle,
        PathValues.API_V1_GROUPS: ApiV1Groups,
        PathValues.API_V1_GROUPS_RULES: ApiV1GroupsRules,
        PathValues.API_V1_GROUPS_RULES_RULE_ID: ApiV1GroupsRulesRuleId,
        PathValues.API_V1_GROUPS_RULES_RULE_ID_LIFECYCLE_ACTIVATE: ApiV1GroupsRulesRuleIdLifecycleActivate,
        PathValues.API_V1_GROUPS_RULES_RULE_ID_LIFECYCLE_DEACTIVATE: ApiV1GroupsRulesRuleIdLifecycleDeactivate,
        PathValues.API_V1_GROUPS_GROUP_ID: ApiV1GroupsGroupId,
        PathValues.API_V1_GROUPS_GROUP_ID_APPS: ApiV1GroupsGroupIdApps,
        PathValues.API_V1_GROUPS_GROUP_ID_ROLES: ApiV1GroupsGroupIdRoles,
        PathValues.API_V1_GROUPS_GROUP_ID_ROLES_ROLE_ID: ApiV1GroupsGroupIdRolesRoleId,
        PathValues.API_V1_GROUPS_GROUP_ID_ROLES_ROLE_ID_TARGETS_CATALOG_APPS: ApiV1GroupsGroupIdRolesRoleIdTargetsCatalogApps,
        PathValues.API_V1_GROUPS_GROUP_ID_ROLES_ROLE_ID_TARGETS_CATALOG_APPS_APP_NAME: ApiV1GroupsGroupIdRolesRoleIdTargetsCatalogAppsAppName,
        PathValues.API_V1_GROUPS_GROUP_ID_ROLES_ROLE_ID_TARGETS_CATALOG_APPS_APP_NAME_APPLICATION_ID: ApiV1GroupsGroupIdRolesRoleIdTargetsCatalogAppsAppNameApplicationId,
        PathValues.API_V1_GROUPS_GROUP_ID_ROLES_ROLE_ID_TARGETS_GROUPS: ApiV1GroupsGroupIdRolesRoleIdTargetsGroups,
        PathValues.API_V1_GROUPS_GROUP_ID_ROLES_ROLE_ID_TARGETS_GROUPS_TARGET_GROUP_ID: ApiV1GroupsGroupIdRolesRoleIdTargetsGroupsTargetGroupId,
        PathValues.API_V1_GROUPS_GROUP_ID_USERS: ApiV1GroupsGroupIdUsers,
        PathValues.API_V1_GROUPS_GROUP_ID_USERS_USER_ID: ApiV1GroupsGroupIdUsersUserId,
        PathValues.API_V1_IDPS: ApiV1Idps,
        PathValues.API_V1_IDPS_CREDENTIALS_KEYS: ApiV1IdpsCredentialsKeys,
        PathValues.API_V1_IDPS_CREDENTIALS_KEYS_KEY_ID: ApiV1IdpsCredentialsKeysKeyId,
        PathValues.API_V1_IDPS_IDP_ID: ApiV1IdpsIdpId,
        PathValues.API_V1_IDPS_IDP_ID_CREDENTIALS_CSRS: ApiV1IdpsIdpIdCredentialsCsrs,
        PathValues.API_V1_IDPS_IDP_ID_CREDENTIALS_CSRS_CSR_ID: ApiV1IdpsIdpIdCredentialsCsrsCsrId,
        PathValues.API_V1_IDPS_IDP_ID_CREDENTIALS_CSRS_CSR_ID_LIFECYCLE_PUBLISH: ApiV1IdpsIdpIdCredentialsCsrsCsrIdLifecyclePublish,
        PathValues.API_V1_IDPS_IDP_ID_CREDENTIALS_KEYS: ApiV1IdpsIdpIdCredentialsKeys,
        PathValues.API_V1_IDPS_IDP_ID_CREDENTIALS_KEYS_GENERATE: ApiV1IdpsIdpIdCredentialsKeysGenerate,
        PathValues.API_V1_IDPS_IDP_ID_CREDENTIALS_KEYS_KEY_ID: ApiV1IdpsIdpIdCredentialsKeysKeyId,
        PathValues.API_V1_IDPS_IDP_ID_CREDENTIALS_KEYS_KEY_ID_CLONE: ApiV1IdpsIdpIdCredentialsKeysKeyIdClone,
        PathValues.API_V1_IDPS_IDP_ID_LIFECYCLE_ACTIVATE: ApiV1IdpsIdpIdLifecycleActivate,
        PathValues.API_V1_IDPS_IDP_ID_LIFECYCLE_DEACTIVATE: ApiV1IdpsIdpIdLifecycleDeactivate,
        PathValues.API_V1_IDPS_IDP_ID_USERS: ApiV1IdpsIdpIdUsers,
        PathValues.API_V1_IDPS_IDP_ID_USERS_USER_ID: ApiV1IdpsIdpIdUsersUserId,
        PathValues.API_V1_IDPS_IDP_ID_USERS_USER_ID_CREDENTIALS_TOKENS: ApiV1IdpsIdpIdUsersUserIdCredentialsTokens,
        PathValues.API_V1_INLINE_HOOKS: ApiV1InlineHooks,
        PathValues.API_V1_INLINE_HOOKS_INLINE_HOOK_ID: ApiV1InlineHooksInlineHookId,
        PathValues.API_V1_INLINE_HOOKS_INLINE_HOOK_ID_EXECUTE: ApiV1InlineHooksInlineHookIdExecute,
        PathValues.API_V1_INLINE_HOOKS_INLINE_HOOK_ID_LIFECYCLE_ACTIVATE: ApiV1InlineHooksInlineHookIdLifecycleActivate,
        PathValues.API_V1_INLINE_HOOKS_INLINE_HOOK_ID_LIFECYCLE_DEACTIVATE: ApiV1InlineHooksInlineHookIdLifecycleDeactivate,
        PathValues.API_V1_LOGS: ApiV1Logs,
        PathValues.API_V1_MAPPINGS: ApiV1Mappings,
        PathValues.API_V1_MAPPINGS_MAPPING_ID: ApiV1MappingsMappingId,
        PathValues.API_V1_META_SCHEMAS_APPS_APP_INSTANCE_ID_DEFAULT: ApiV1MetaSchemasAppsAppInstanceIdDefault,
        PathValues.API_V1_META_SCHEMAS_GROUP_DEFAULT: ApiV1MetaSchemasGroupDefault,
        PathValues.API_V1_META_SCHEMAS_USER_LINKED_OBJECTS: ApiV1MetaSchemasUserLinkedObjects,
        PathValues.API_V1_META_SCHEMAS_USER_LINKED_OBJECTS_LINKED_OBJECT_NAME: ApiV1MetaSchemasUserLinkedObjectsLinkedObjectName,
        PathValues.API_V1_META_SCHEMAS_USER_SCHEMA_ID: ApiV1MetaSchemasUserSchemaId,
        PathValues.API_V1_META_TYPES_USER: ApiV1MetaTypesUser,
        PathValues.API_V1_META_TYPES_USER_TYPE_ID: ApiV1MetaTypesUserTypeId,
        PathValues.API_V1_ORG: ApiV1Org,
        PathValues.API_V1_ORG_CONTACTS: ApiV1OrgContacts,
        PathValues.API_V1_ORG_CONTACTS_CONTACT_TYPE: ApiV1OrgContactsContactType,
        PathValues.API_V1_ORG_LOGO: ApiV1OrgLogo,
        PathValues.API_V1_ORG_PREFERENCES: ApiV1OrgPreferences,
        PathValues.API_V1_ORG_PREFERENCES_HIDE_END_USER_FOOTER: ApiV1OrgPreferencesHideEndUserFooter,
        PathValues.API_V1_ORG_PREFERENCES_SHOW_END_USER_FOOTER: ApiV1OrgPreferencesShowEndUserFooter,
        PathValues.API_V1_ORG_PRIVACY_OKTA_COMMUNICATION: ApiV1OrgPrivacyOktaCommunication,
        PathValues.API_V1_ORG_PRIVACY_OKTA_COMMUNICATION_OPT_IN: ApiV1OrgPrivacyOktaCommunicationOptIn,
        PathValues.API_V1_ORG_PRIVACY_OKTA_COMMUNICATION_OPT_OUT: ApiV1OrgPrivacyOktaCommunicationOptOut,
        PathValues.API_V1_ORG_PRIVACY_OKTA_SUPPORT: ApiV1OrgPrivacyOktaSupport,
        PathValues.API_V1_ORG_PRIVACY_OKTA_SUPPORT_EXTEND: ApiV1OrgPrivacyOktaSupportExtend,
        PathValues.API_V1_ORG_PRIVACY_OKTA_SUPPORT_GRANT: ApiV1OrgPrivacyOktaSupportGrant,
        PathValues.API_V1_ORG_PRIVACY_OKTA_SUPPORT_REVOKE: ApiV1OrgPrivacyOktaSupportRevoke,
        PathValues.API_V1_POLICIES: ApiV1Policies,
        PathValues.API_V1_POLICIES_POLICY_ID: ApiV1PoliciesPolicyId,
        PathValues.API_V1_POLICIES_POLICY_ID_LIFECYCLE_ACTIVATE: ApiV1PoliciesPolicyIdLifecycleActivate,
        PathValues.API_V1_POLICIES_POLICY_ID_LIFECYCLE_DEACTIVATE: ApiV1PoliciesPolicyIdLifecycleDeactivate,
        PathValues.API_V1_POLICIES_POLICY_ID_RULES: ApiV1PoliciesPolicyIdRules,
        PathValues.API_V1_POLICIES_POLICY_ID_RULES_RULE_ID: ApiV1PoliciesPolicyIdRulesRuleId,
        PathValues.API_V1_POLICIES_POLICY_ID_RULES_RULE_ID_LIFECYCLE_ACTIVATE: ApiV1PoliciesPolicyIdRulesRuleIdLifecycleActivate,
        PathValues.API_V1_POLICIES_POLICY_ID_RULES_RULE_ID_LIFECYCLE_DEACTIVATE: ApiV1PoliciesPolicyIdRulesRuleIdLifecycleDeactivate,
        PathValues.API_V1_ROLES_ROLE_TYPE_OR_ROLE_ID_SUBSCRIPTIONS: ApiV1RolesRoleTypeOrRoleIdSubscriptions,
        PathValues.API_V1_ROLES_ROLE_TYPE_OR_ROLE_ID_SUBSCRIPTIONS_NOTIFICATION_TYPE: ApiV1RolesRoleTypeOrRoleIdSubscriptionsNotificationType,
        PathValues.API_V1_ROLES_ROLE_TYPE_OR_ROLE_ID_SUBSCRIPTIONS_NOTIFICATION_TYPE_SUBSCRIBE: ApiV1RolesRoleTypeOrRoleIdSubscriptionsNotificationTypeSubscribe,
        PathValues.API_V1_ROLES_ROLE_TYPE_OR_ROLE_ID_SUBSCRIPTIONS_NOTIFICATION_TYPE_UNSUBSCRIBE: ApiV1RolesRoleTypeOrRoleIdSubscriptionsNotificationTypeUnsubscribe,
        PathValues.API_V1_SESSIONS: ApiV1Sessions,
        PathValues.API_V1_SESSIONS_SESSION_ID: ApiV1SessionsSessionId,
        PathValues.API_V1_SESSIONS_SESSION_ID_LIFECYCLE_REFRESH: ApiV1SessionsSessionIdLifecycleRefresh,
        PathValues.API_V1_TEMPLATES_SMS: ApiV1TemplatesSms,
        PathValues.API_V1_TEMPLATES_SMS_TEMPLATE_ID: ApiV1TemplatesSmsTemplateId,
        PathValues.API_V1_THREATS_CONFIGURATION: ApiV1ThreatsConfiguration,
        PathValues.API_V1_TRUSTED_ORIGINS: ApiV1TrustedOrigins,
        PathValues.API_V1_TRUSTED_ORIGINS_TRUSTED_ORIGIN_ID: ApiV1TrustedOriginsTrustedOriginId,
        PathValues.API_V1_TRUSTED_ORIGINS_TRUSTED_ORIGIN_ID_LIFECYCLE_ACTIVATE: ApiV1TrustedOriginsTrustedOriginIdLifecycleActivate,
        PathValues.API_V1_TRUSTED_ORIGINS_TRUSTED_ORIGIN_ID_LIFECYCLE_DEACTIVATE: ApiV1TrustedOriginsTrustedOriginIdLifecycleDeactivate,
        PathValues.API_V1_USERS: ApiV1Users,
        PathValues.API_V1_USERS_ASSOCIATED_USER_ID_LINKED_OBJECTS_PRIMARY_RELATIONSHIP_NAME_PRIMARY_USER_ID: ApiV1UsersAssociatedUserIdLinkedObjectsPrimaryRelationshipNamePrimaryUserId,
        PathValues.API_V1_USERS_USER_ID: ApiV1UsersUserId,
        PathValues.API_V1_USERS_USER_ID_APP_LINKS: ApiV1UsersUserIdAppLinks,
        PathValues.API_V1_USERS_USER_ID_CLIENTS: ApiV1UsersUserIdClients,
        PathValues.API_V1_USERS_USER_ID_CLIENTS_CLIENT_ID_GRANTS: ApiV1UsersUserIdClientsClientIdGrants,
        PathValues.API_V1_USERS_USER_ID_CLIENTS_CLIENT_ID_TOKENS: ApiV1UsersUserIdClientsClientIdTokens,
        PathValues.API_V1_USERS_USER_ID_CLIENTS_CLIENT_ID_TOKENS_TOKEN_ID: ApiV1UsersUserIdClientsClientIdTokensTokenId,
        PathValues.API_V1_USERS_USER_ID_CREDENTIALS_CHANGE_PASSWORD: ApiV1UsersUserIdCredentialsChangePassword,
        PathValues.API_V1_USERS_USER_ID_CREDENTIALS_CHANGE_RECOVERY_QUESTION: ApiV1UsersUserIdCredentialsChangeRecoveryQuestion,
        PathValues.API_V1_USERS_USER_ID_CREDENTIALS_FORGOT_PASSWORD: ApiV1UsersUserIdCredentialsForgotPassword,
        PathValues.API_V1_USERS_USER_ID_FACTORS: ApiV1UsersUserIdFactors,
        PathValues.API_V1_USERS_USER_ID_FACTORS_CATALOG: ApiV1UsersUserIdFactorsCatalog,
        PathValues.API_V1_USERS_USER_ID_FACTORS_QUESTIONS: ApiV1UsersUserIdFactorsQuestions,
        PathValues.API_V1_USERS_USER_ID_FACTORS_FACTOR_ID: ApiV1UsersUserIdFactorsFactorId,
        PathValues.API_V1_USERS_USER_ID_FACTORS_FACTOR_ID_LIFECYCLE_ACTIVATE: ApiV1UsersUserIdFactorsFactorIdLifecycleActivate,
        PathValues.API_V1_USERS_USER_ID_FACTORS_FACTOR_ID_TRANSACTIONS_TRANSACTION_ID: ApiV1UsersUserIdFactorsFactorIdTransactionsTransactionId,
        PathValues.API_V1_USERS_USER_ID_FACTORS_FACTOR_ID_VERIFY: ApiV1UsersUserIdFactorsFactorIdVerify,
        PathValues.API_V1_USERS_USER_ID_GRANTS: ApiV1UsersUserIdGrants,
        PathValues.API_V1_USERS_USER_ID_GRANTS_GRANT_ID: ApiV1UsersUserIdGrantsGrantId,
        PathValues.API_V1_USERS_USER_ID_GROUPS: ApiV1UsersUserIdGroups,
        PathValues.API_V1_USERS_USER_ID_IDPS: ApiV1UsersUserIdIdps,
        PathValues.API_V1_USERS_USER_ID_LIFECYCLE_ACTIVATE: ApiV1UsersUserIdLifecycleActivate,
        PathValues.API_V1_USERS_USER_ID_LIFECYCLE_DEACTIVATE: ApiV1UsersUserIdLifecycleDeactivate,
        PathValues.API_V1_USERS_USER_ID_LIFECYCLE_EXPIRE_PASSWORDTEMP_PASSWORDFALSE: ApiV1UsersUserIdLifecycleExpirePasswordtempPasswordfalse,
        PathValues.API_V1_USERS_USER_ID_LIFECYCLE_EXPIRE_PASSWORDTEMP_PASSWORDTRUE: ApiV1UsersUserIdLifecycleExpirePasswordtempPasswordtrue,
        PathValues.API_V1_USERS_USER_ID_LIFECYCLE_REACTIVATE: ApiV1UsersUserIdLifecycleReactivate,
        PathValues.API_V1_USERS_USER_ID_LIFECYCLE_RESET_FACTORS: ApiV1UsersUserIdLifecycleResetFactors,
        PathValues.API_V1_USERS_USER_ID_LIFECYCLE_RESET_PASSWORD: ApiV1UsersUserIdLifecycleResetPassword,
        PathValues.API_V1_USERS_USER_ID_LIFECYCLE_SUSPEND: ApiV1UsersUserIdLifecycleSuspend,
        PathValues.API_V1_USERS_USER_ID_LIFECYCLE_UNLOCK: ApiV1UsersUserIdLifecycleUnlock,
        PathValues.API_V1_USERS_USER_ID_LIFECYCLE_UNSUSPEND: ApiV1UsersUserIdLifecycleUnsuspend,
        PathValues.API_V1_USERS_USER_ID_LINKED_OBJECTS_RELATIONSHIP_NAME: ApiV1UsersUserIdLinkedObjectsRelationshipName,
        PathValues.API_V1_USERS_USER_ID_ROLES: ApiV1UsersUserIdRoles,
        PathValues.API_V1_USERS_USER_ID_ROLES_ROLE_ID: ApiV1UsersUserIdRolesRoleId,
        PathValues.API_V1_USERS_USER_ID_ROLES_ROLE_ID_TARGETS_CATALOG_APPS: ApiV1UsersUserIdRolesRoleIdTargetsCatalogApps,
        PathValues.API_V1_USERS_USER_ID_ROLES_ROLE_ID_TARGETS_CATALOG_APPS_APP_NAME: ApiV1UsersUserIdRolesRoleIdTargetsCatalogAppsAppName,
        PathValues.API_V1_USERS_USER_ID_ROLES_ROLE_ID_TARGETS_CATALOG_APPS_APP_NAME_APPLICATION_ID: ApiV1UsersUserIdRolesRoleIdTargetsCatalogAppsAppNameApplicationId,
        PathValues.API_V1_USERS_USER_ID_ROLES_ROLE_ID_TARGETS_GROUPS: ApiV1UsersUserIdRolesRoleIdTargetsGroups,
        PathValues.API_V1_USERS_USER_ID_ROLES_ROLE_ID_TARGETS_GROUPS_GROUP_ID: ApiV1UsersUserIdRolesRoleIdTargetsGroupsGroupId,
        PathValues.API_V1_USERS_USER_ID_SESSIONS: ApiV1UsersUserIdSessions,
        PathValues.API_V1_USERS_USER_ID_SUBSCRIPTIONS: ApiV1UsersUserIdSubscriptions,
        PathValues.API_V1_USERS_USER_ID_SUBSCRIPTIONS_NOTIFICATION_TYPE: ApiV1UsersUserIdSubscriptionsNotificationType,
        PathValues.API_V1_USERS_USER_ID_SUBSCRIPTIONS_NOTIFICATION_TYPE_SUBSCRIBE: ApiV1UsersUserIdSubscriptionsNotificationTypeSubscribe,
        PathValues.API_V1_USERS_USER_ID_SUBSCRIPTIONS_NOTIFICATION_TYPE_UNSUBSCRIBE: ApiV1UsersUserIdSubscriptionsNotificationTypeUnsubscribe,
        PathValues.API_V1_ZONES: ApiV1Zones,
        PathValues.API_V1_ZONES_ZONE_ID: ApiV1ZonesZoneId,
        PathValues.API_V1_ZONES_ZONE_ID_LIFECYCLE_ACTIVATE: ApiV1ZonesZoneIdLifecycleActivate,
        PathValues.API_V1_ZONES_ZONE_ID_LIFECYCLE_DEACTIVATE: ApiV1ZonesZoneIdLifecycleDeactivate,
    }
)

path_to_api = PathToApi(
    {
        PathValues.API_V1_APPS: ApiV1Apps,
        PathValues.API_V1_APPS_APP_ID: ApiV1AppsAppId,
        PathValues.API_V1_APPS_APP_ID_CONNECTIONS_DEFAULT: ApiV1AppsAppIdConnectionsDefault,
        PathValues.API_V1_APPS_APP_ID_CONNECTIONS_DEFAULT_LIFECYCLE_ACTIVATE: ApiV1AppsAppIdConnectionsDefaultLifecycleActivate,
        PathValues.API_V1_APPS_APP_ID_CONNECTIONS_DEFAULT_LIFECYCLE_DEACTIVATE: ApiV1AppsAppIdConnectionsDefaultLifecycleDeactivate,
        PathValues.API_V1_APPS_APP_ID_CREDENTIALS_CSRS: ApiV1AppsAppIdCredentialsCsrs,
        PathValues.API_V1_APPS_APP_ID_CREDENTIALS_CSRS_CSR_ID: ApiV1AppsAppIdCredentialsCsrsCsrId,
        PathValues.API_V1_APPS_APP_ID_CREDENTIALS_CSRS_CSR_ID_LIFECYCLE_PUBLISH: ApiV1AppsAppIdCredentialsCsrsCsrIdLifecyclePublish,
        PathValues.API_V1_APPS_APP_ID_CREDENTIALS_KEYS: ApiV1AppsAppIdCredentialsKeys,
        PathValues.API_V1_APPS_APP_ID_CREDENTIALS_KEYS_GENERATE: ApiV1AppsAppIdCredentialsKeysGenerate,
        PathValues.API_V1_APPS_APP_ID_CREDENTIALS_KEYS_KEY_ID: ApiV1AppsAppIdCredentialsKeysKeyId,
        PathValues.API_V1_APPS_APP_ID_CREDENTIALS_KEYS_KEY_ID_CLONE: ApiV1AppsAppIdCredentialsKeysKeyIdClone,
        PathValues.API_V1_APPS_APP_ID_CREDENTIALS_SECRETS: ApiV1AppsAppIdCredentialsSecrets,
        PathValues.API_V1_APPS_APP_ID_CREDENTIALS_SECRETS_SECRET_ID: ApiV1AppsAppIdCredentialsSecretsSecretId,
        PathValues.API_V1_APPS_APP_ID_CREDENTIALS_SECRETS_SECRET_ID_LIFECYCLE_ACTIVATE: ApiV1AppsAppIdCredentialsSecretsSecretIdLifecycleActivate,
        PathValues.API_V1_APPS_APP_ID_CREDENTIALS_SECRETS_SECRET_ID_LIFECYCLE_DEACTIVATE: ApiV1AppsAppIdCredentialsSecretsSecretIdLifecycleDeactivate,
        PathValues.API_V1_APPS_APP_ID_FEATURES: ApiV1AppsAppIdFeatures,
        PathValues.API_V1_APPS_APP_ID_FEATURES_NAME: ApiV1AppsAppIdFeaturesName,
        PathValues.API_V1_APPS_APP_ID_GRANTS: ApiV1AppsAppIdGrants,
        PathValues.API_V1_APPS_APP_ID_GRANTS_GRANT_ID: ApiV1AppsAppIdGrantsGrantId,
        PathValues.API_V1_APPS_APP_ID_GROUPS: ApiV1AppsAppIdGroups,
        PathValues.API_V1_APPS_APP_ID_GROUPS_GROUP_ID: ApiV1AppsAppIdGroupsGroupId,
        PathValues.API_V1_APPS_APP_ID_LIFECYCLE_ACTIVATE: ApiV1AppsAppIdLifecycleActivate,
        PathValues.API_V1_APPS_APP_ID_LIFECYCLE_DEACTIVATE: ApiV1AppsAppIdLifecycleDeactivate,
        PathValues.API_V1_APPS_APP_ID_LOGO: ApiV1AppsAppIdLogo,
        PathValues.API_V1_APPS_APP_ID_POLICIES_POLICY_ID: ApiV1AppsAppIdPoliciesPolicyId,
        PathValues.API_V1_APPS_APP_ID_SSO_SAML_METADATA: ApiV1AppsAppIdSsoSamlMetadata,
        PathValues.API_V1_APPS_APP_ID_TOKENS: ApiV1AppsAppIdTokens,
        PathValues.API_V1_APPS_APP_ID_TOKENS_TOKEN_ID: ApiV1AppsAppIdTokensTokenId,
        PathValues.API_V1_APPS_APP_ID_USERS: ApiV1AppsAppIdUsers,
        PathValues.API_V1_APPS_APP_ID_USERS_USER_ID: ApiV1AppsAppIdUsersUserId,
        PathValues.API_V1_AUTHENTICATORS: ApiV1Authenticators,
        PathValues.API_V1_AUTHENTICATORS_AUTHENTICATOR_ID: ApiV1AuthenticatorsAuthenticatorId,
        PathValues.API_V1_AUTHENTICATORS_AUTHENTICATOR_ID_LIFECYCLE_ACTIVATE: ApiV1AuthenticatorsAuthenticatorIdLifecycleActivate,
        PathValues.API_V1_AUTHENTICATORS_AUTHENTICATOR_ID_LIFECYCLE_DEACTIVATE: ApiV1AuthenticatorsAuthenticatorIdLifecycleDeactivate,
        PathValues.API_V1_AUTHORIZATION_SERVERS: ApiV1AuthorizationServers,
        PathValues.API_V1_AUTHORIZATION_SERVERS_AUTH_SERVER_ID: ApiV1AuthorizationServersAuthServerId,
        PathValues.API_V1_AUTHORIZATION_SERVERS_AUTH_SERVER_ID_CLAIMS: ApiV1AuthorizationServersAuthServerIdClaims,
        PathValues.API_V1_AUTHORIZATION_SERVERS_AUTH_SERVER_ID_CLAIMS_CLAIM_ID: ApiV1AuthorizationServersAuthServerIdClaimsClaimId,
        PathValues.API_V1_AUTHORIZATION_SERVERS_AUTH_SERVER_ID_CLIENTS: ApiV1AuthorizationServersAuthServerIdClients,
        PathValues.API_V1_AUTHORIZATION_SERVERS_AUTH_SERVER_ID_CLIENTS_CLIENT_ID_TOKENS: ApiV1AuthorizationServersAuthServerIdClientsClientIdTokens,
        PathValues.API_V1_AUTHORIZATION_SERVERS_AUTH_SERVER_ID_CLIENTS_CLIENT_ID_TOKENS_TOKEN_ID: ApiV1AuthorizationServersAuthServerIdClientsClientIdTokensTokenId,
        PathValues.API_V1_AUTHORIZATION_SERVERS_AUTH_SERVER_ID_CREDENTIALS_KEYS: ApiV1AuthorizationServersAuthServerIdCredentialsKeys,
        PathValues.API_V1_AUTHORIZATION_SERVERS_AUTH_SERVER_ID_CREDENTIALS_LIFECYCLE_KEY_ROTATE: ApiV1AuthorizationServersAuthServerIdCredentialsLifecycleKeyRotate,
        PathValues.API_V1_AUTHORIZATION_SERVERS_AUTH_SERVER_ID_LIFECYCLE_ACTIVATE: ApiV1AuthorizationServersAuthServerIdLifecycleActivate,
        PathValues.API_V1_AUTHORIZATION_SERVERS_AUTH_SERVER_ID_LIFECYCLE_DEACTIVATE: ApiV1AuthorizationServersAuthServerIdLifecycleDeactivate,
        PathValues.API_V1_AUTHORIZATION_SERVERS_AUTH_SERVER_ID_POLICIES: ApiV1AuthorizationServersAuthServerIdPolicies,
        PathValues.API_V1_AUTHORIZATION_SERVERS_AUTH_SERVER_ID_POLICIES_POLICY_ID: ApiV1AuthorizationServersAuthServerIdPoliciesPolicyId,
        PathValues.API_V1_AUTHORIZATION_SERVERS_AUTH_SERVER_ID_POLICIES_POLICY_ID_LIFECYCLE_ACTIVATE: ApiV1AuthorizationServersAuthServerIdPoliciesPolicyIdLifecycleActivate,
        PathValues.API_V1_AUTHORIZATION_SERVERS_AUTH_SERVER_ID_POLICIES_POLICY_ID_LIFECYCLE_DEACTIVATE: ApiV1AuthorizationServersAuthServerIdPoliciesPolicyIdLifecycleDeactivate,
        PathValues.API_V1_AUTHORIZATION_SERVERS_AUTH_SERVER_ID_POLICIES_POLICY_ID_RULES: ApiV1AuthorizationServersAuthServerIdPoliciesPolicyIdRules,
        PathValues.API_V1_AUTHORIZATION_SERVERS_AUTH_SERVER_ID_POLICIES_POLICY_ID_RULES_RULE_ID: ApiV1AuthorizationServersAuthServerIdPoliciesPolicyIdRulesRuleId,
        PathValues.API_V1_AUTHORIZATION_SERVERS_AUTH_SERVER_ID_POLICIES_POLICY_ID_RULES_RULE_ID_LIFECYCLE_ACTIVATE: ApiV1AuthorizationServersAuthServerIdPoliciesPolicyIdRulesRuleIdLifecycleActivate,
        PathValues.API_V1_AUTHORIZATION_SERVERS_AUTH_SERVER_ID_POLICIES_POLICY_ID_RULES_RULE_ID_LIFECYCLE_DEACTIVATE: ApiV1AuthorizationServersAuthServerIdPoliciesPolicyIdRulesRuleIdLifecycleDeactivate,
        PathValues.API_V1_AUTHORIZATION_SERVERS_AUTH_SERVER_ID_SCOPES: ApiV1AuthorizationServersAuthServerIdScopes,
        PathValues.API_V1_AUTHORIZATION_SERVERS_AUTH_SERVER_ID_SCOPES_SCOPE_ID: ApiV1AuthorizationServersAuthServerIdScopesScopeId,
        PathValues.API_V1_BRANDS: ApiV1Brands,
        PathValues.API_V1_BRANDS_BRAND_ID: ApiV1BrandsBrandId,
        PathValues.API_V1_BRANDS_BRAND_ID_TEMPLATES_EMAIL: ApiV1BrandsBrandIdTemplatesEmail,
        PathValues.API_V1_BRANDS_BRAND_ID_TEMPLATES_EMAIL_TEMPLATE_NAME: ApiV1BrandsBrandIdTemplatesEmailTemplateName,
        PathValues.API_V1_BRANDS_BRAND_ID_TEMPLATES_EMAIL_TEMPLATE_NAME_CUSTOMIZATIONS: ApiV1BrandsBrandIdTemplatesEmailTemplateNameCustomizations,
        PathValues.API_V1_BRANDS_BRAND_ID_TEMPLATES_EMAIL_TEMPLATE_NAME_CUSTOMIZATIONS_CUSTOMIZATION_ID: ApiV1BrandsBrandIdTemplatesEmailTemplateNameCustomizationsCustomizationId,
        PathValues.API_V1_BRANDS_BRAND_ID_TEMPLATES_EMAIL_TEMPLATE_NAME_CUSTOMIZATIONS_CUSTOMIZATION_ID_PREVIEW: ApiV1BrandsBrandIdTemplatesEmailTemplateNameCustomizationsCustomizationIdPreview,
        PathValues.API_V1_BRANDS_BRAND_ID_TEMPLATES_EMAIL_TEMPLATE_NAME_DEFAULTCONTENT: ApiV1BrandsBrandIdTemplatesEmailTemplateNameDefaultContent,
        PathValues.API_V1_BRANDS_BRAND_ID_TEMPLATES_EMAIL_TEMPLATE_NAME_DEFAULTCONTENT_PREVIEW: ApiV1BrandsBrandIdTemplatesEmailTemplateNameDefaultContentPreview,
        PathValues.API_V1_BRANDS_BRAND_ID_TEMPLATES_EMAIL_TEMPLATE_NAME_TEST: ApiV1BrandsBrandIdTemplatesEmailTemplateNameTest,
        PathValues.API_V1_BRANDS_BRAND_ID_THEMES: ApiV1BrandsBrandIdThemes,
        PathValues.API_V1_BRANDS_BRAND_ID_THEMES_THEME_ID: ApiV1BrandsBrandIdThemesThemeId,
        PathValues.API_V1_BRANDS_BRAND_ID_THEMES_THEME_ID_BACKGROUNDIMAGE: ApiV1BrandsBrandIdThemesThemeIdBackgroundImage,
        PathValues.API_V1_BRANDS_BRAND_ID_THEMES_THEME_ID_FAVICON: ApiV1BrandsBrandIdThemesThemeIdFavicon,
        PathValues.API_V1_BRANDS_BRAND_ID_THEMES_THEME_ID_LOGO: ApiV1BrandsBrandIdThemesThemeIdLogo,
        PathValues.API_V1_DOMAINS: ApiV1Domains,
        PathValues.API_V1_DOMAINS_DOMAIN_ID: ApiV1DomainsDomainId,
        PathValues.API_V1_DOMAINS_DOMAIN_ID_CERTIFICATE: ApiV1DomainsDomainIdCertificate,
        PathValues.API_V1_DOMAINS_DOMAIN_ID_VERIFY: ApiV1DomainsDomainIdVerify,
        PathValues.API_V1_EVENT_HOOKS: ApiV1EventHooks,
        PathValues.API_V1_EVENT_HOOKS_EVENT_HOOK_ID: ApiV1EventHooksEventHookId,
        PathValues.API_V1_EVENT_HOOKS_EVENT_HOOK_ID_LIFECYCLE_ACTIVATE: ApiV1EventHooksEventHookIdLifecycleActivate,
        PathValues.API_V1_EVENT_HOOKS_EVENT_HOOK_ID_LIFECYCLE_DEACTIVATE: ApiV1EventHooksEventHookIdLifecycleDeactivate,
        PathValues.API_V1_EVENT_HOOKS_EVENT_HOOK_ID_LIFECYCLE_VERIFY: ApiV1EventHooksEventHookIdLifecycleVerify,
        PathValues.API_V1_FEATURES: ApiV1Features,
        PathValues.API_V1_FEATURES_FEATURE_ID: ApiV1FeaturesFeatureId,
        PathValues.API_V1_FEATURES_FEATURE_ID_DEPENDENCIES: ApiV1FeaturesFeatureIdDependencies,
        PathValues.API_V1_FEATURES_FEATURE_ID_DEPENDENTS: ApiV1FeaturesFeatureIdDependents,
        PathValues.API_V1_FEATURES_FEATURE_ID_LIFECYCLE: ApiV1FeaturesFeatureIdLifecycle,
        PathValues.API_V1_GROUPS: ApiV1Groups,
        PathValues.API_V1_GROUPS_RULES: ApiV1GroupsRules,
        PathValues.API_V1_GROUPS_RULES_RULE_ID: ApiV1GroupsRulesRuleId,
        PathValues.API_V1_GROUPS_RULES_RULE_ID_LIFECYCLE_ACTIVATE: ApiV1GroupsRulesRuleIdLifecycleActivate,
        PathValues.API_V1_GROUPS_RULES_RULE_ID_LIFECYCLE_DEACTIVATE: ApiV1GroupsRulesRuleIdLifecycleDeactivate,
        PathValues.API_V1_GROUPS_GROUP_ID: ApiV1GroupsGroupId,
        PathValues.API_V1_GROUPS_GROUP_ID_APPS: ApiV1GroupsGroupIdApps,
        PathValues.API_V1_GROUPS_GROUP_ID_ROLES: ApiV1GroupsGroupIdRoles,
        PathValues.API_V1_GROUPS_GROUP_ID_ROLES_ROLE_ID: ApiV1GroupsGroupIdRolesRoleId,
        PathValues.API_V1_GROUPS_GROUP_ID_ROLES_ROLE_ID_TARGETS_CATALOG_APPS: ApiV1GroupsGroupIdRolesRoleIdTargetsCatalogApps,
        PathValues.API_V1_GROUPS_GROUP_ID_ROLES_ROLE_ID_TARGETS_CATALOG_APPS_APP_NAME: ApiV1GroupsGroupIdRolesRoleIdTargetsCatalogAppsAppName,
        PathValues.API_V1_GROUPS_GROUP_ID_ROLES_ROLE_ID_TARGETS_CATALOG_APPS_APP_NAME_APPLICATION_ID: ApiV1GroupsGroupIdRolesRoleIdTargetsCatalogAppsAppNameApplicationId,
        PathValues.API_V1_GROUPS_GROUP_ID_ROLES_ROLE_ID_TARGETS_GROUPS: ApiV1GroupsGroupIdRolesRoleIdTargetsGroups,
        PathValues.API_V1_GROUPS_GROUP_ID_ROLES_ROLE_ID_TARGETS_GROUPS_TARGET_GROUP_ID: ApiV1GroupsGroupIdRolesRoleIdTargetsGroupsTargetGroupId,
        PathValues.API_V1_GROUPS_GROUP_ID_USERS: ApiV1GroupsGroupIdUsers,
        PathValues.API_V1_GROUPS_GROUP_ID_USERS_USER_ID: ApiV1GroupsGroupIdUsersUserId,
        PathValues.API_V1_IDPS: ApiV1Idps,
        PathValues.API_V1_IDPS_CREDENTIALS_KEYS: ApiV1IdpsCredentialsKeys,
        PathValues.API_V1_IDPS_CREDENTIALS_KEYS_KEY_ID: ApiV1IdpsCredentialsKeysKeyId,
        PathValues.API_V1_IDPS_IDP_ID: ApiV1IdpsIdpId,
        PathValues.API_V1_IDPS_IDP_ID_CREDENTIALS_CSRS: ApiV1IdpsIdpIdCredentialsCsrs,
        PathValues.API_V1_IDPS_IDP_ID_CREDENTIALS_CSRS_CSR_ID: ApiV1IdpsIdpIdCredentialsCsrsCsrId,
        PathValues.API_V1_IDPS_IDP_ID_CREDENTIALS_CSRS_CSR_ID_LIFECYCLE_PUBLISH: ApiV1IdpsIdpIdCredentialsCsrsCsrIdLifecyclePublish,
        PathValues.API_V1_IDPS_IDP_ID_CREDENTIALS_KEYS: ApiV1IdpsIdpIdCredentialsKeys,
        PathValues.API_V1_IDPS_IDP_ID_CREDENTIALS_KEYS_GENERATE: ApiV1IdpsIdpIdCredentialsKeysGenerate,
        PathValues.API_V1_IDPS_IDP_ID_CREDENTIALS_KEYS_KEY_ID: ApiV1IdpsIdpIdCredentialsKeysKeyId,
        PathValues.API_V1_IDPS_IDP_ID_CREDENTIALS_KEYS_KEY_ID_CLONE: ApiV1IdpsIdpIdCredentialsKeysKeyIdClone,
        PathValues.API_V1_IDPS_IDP_ID_LIFECYCLE_ACTIVATE: ApiV1IdpsIdpIdLifecycleActivate,
        PathValues.API_V1_IDPS_IDP_ID_LIFECYCLE_DEACTIVATE: ApiV1IdpsIdpIdLifecycleDeactivate,
        PathValues.API_V1_IDPS_IDP_ID_USERS: ApiV1IdpsIdpIdUsers,
        PathValues.API_V1_IDPS_IDP_ID_USERS_USER_ID: ApiV1IdpsIdpIdUsersUserId,
        PathValues.API_V1_IDPS_IDP_ID_USERS_USER_ID_CREDENTIALS_TOKENS: ApiV1IdpsIdpIdUsersUserIdCredentialsTokens,
        PathValues.API_V1_INLINE_HOOKS: ApiV1InlineHooks,
        PathValues.API_V1_INLINE_HOOKS_INLINE_HOOK_ID: ApiV1InlineHooksInlineHookId,
        PathValues.API_V1_INLINE_HOOKS_INLINE_HOOK_ID_EXECUTE: ApiV1InlineHooksInlineHookIdExecute,
        PathValues.API_V1_INLINE_HOOKS_INLINE_HOOK_ID_LIFECYCLE_ACTIVATE: ApiV1InlineHooksInlineHookIdLifecycleActivate,
        PathValues.API_V1_INLINE_HOOKS_INLINE_HOOK_ID_LIFECYCLE_DEACTIVATE: ApiV1InlineHooksInlineHookIdLifecycleDeactivate,
        PathValues.API_V1_LOGS: ApiV1Logs,
        PathValues.API_V1_MAPPINGS: ApiV1Mappings,
        PathValues.API_V1_MAPPINGS_MAPPING_ID: ApiV1MappingsMappingId,
        PathValues.API_V1_META_SCHEMAS_APPS_APP_INSTANCE_ID_DEFAULT: ApiV1MetaSchemasAppsAppInstanceIdDefault,
        PathValues.API_V1_META_SCHEMAS_GROUP_DEFAULT: ApiV1MetaSchemasGroupDefault,
        PathValues.API_V1_META_SCHEMAS_USER_LINKED_OBJECTS: ApiV1MetaSchemasUserLinkedObjects,
        PathValues.API_V1_META_SCHEMAS_USER_LINKED_OBJECTS_LINKED_OBJECT_NAME: ApiV1MetaSchemasUserLinkedObjectsLinkedObjectName,
        PathValues.API_V1_META_SCHEMAS_USER_SCHEMA_ID: ApiV1MetaSchemasUserSchemaId,
        PathValues.API_V1_META_TYPES_USER: ApiV1MetaTypesUser,
        PathValues.API_V1_META_TYPES_USER_TYPE_ID: ApiV1MetaTypesUserTypeId,
        PathValues.API_V1_ORG: ApiV1Org,
        PathValues.API_V1_ORG_CONTACTS: ApiV1OrgContacts,
        PathValues.API_V1_ORG_CONTACTS_CONTACT_TYPE: ApiV1OrgContactsContactType,
        PathValues.API_V1_ORG_LOGO: ApiV1OrgLogo,
        PathValues.API_V1_ORG_PREFERENCES: ApiV1OrgPreferences,
        PathValues.API_V1_ORG_PREFERENCES_HIDE_END_USER_FOOTER: ApiV1OrgPreferencesHideEndUserFooter,
        PathValues.API_V1_ORG_PREFERENCES_SHOW_END_USER_FOOTER: ApiV1OrgPreferencesShowEndUserFooter,
        PathValues.API_V1_ORG_PRIVACY_OKTA_COMMUNICATION: ApiV1OrgPrivacyOktaCommunication,
        PathValues.API_V1_ORG_PRIVACY_OKTA_COMMUNICATION_OPT_IN: ApiV1OrgPrivacyOktaCommunicationOptIn,
        PathValues.API_V1_ORG_PRIVACY_OKTA_COMMUNICATION_OPT_OUT: ApiV1OrgPrivacyOktaCommunicationOptOut,
        PathValues.API_V1_ORG_PRIVACY_OKTA_SUPPORT: ApiV1OrgPrivacyOktaSupport,
        PathValues.API_V1_ORG_PRIVACY_OKTA_SUPPORT_EXTEND: ApiV1OrgPrivacyOktaSupportExtend,
        PathValues.API_V1_ORG_PRIVACY_OKTA_SUPPORT_GRANT: ApiV1OrgPrivacyOktaSupportGrant,
        PathValues.API_V1_ORG_PRIVACY_OKTA_SUPPORT_REVOKE: ApiV1OrgPrivacyOktaSupportRevoke,
        PathValues.API_V1_POLICIES: ApiV1Policies,
        PathValues.API_V1_POLICIES_POLICY_ID: ApiV1PoliciesPolicyId,
        PathValues.API_V1_POLICIES_POLICY_ID_LIFECYCLE_ACTIVATE: ApiV1PoliciesPolicyIdLifecycleActivate,
        PathValues.API_V1_POLICIES_POLICY_ID_LIFECYCLE_DEACTIVATE: ApiV1PoliciesPolicyIdLifecycleDeactivate,
        PathValues.API_V1_POLICIES_POLICY_ID_RULES: ApiV1PoliciesPolicyIdRules,
        PathValues.API_V1_POLICIES_POLICY_ID_RULES_RULE_ID: ApiV1PoliciesPolicyIdRulesRuleId,
        PathValues.API_V1_POLICIES_POLICY_ID_RULES_RULE_ID_LIFECYCLE_ACTIVATE: ApiV1PoliciesPolicyIdRulesRuleIdLifecycleActivate,
        PathValues.API_V1_POLICIES_POLICY_ID_RULES_RULE_ID_LIFECYCLE_DEACTIVATE: ApiV1PoliciesPolicyIdRulesRuleIdLifecycleDeactivate,
        PathValues.API_V1_ROLES_ROLE_TYPE_OR_ROLE_ID_SUBSCRIPTIONS: ApiV1RolesRoleTypeOrRoleIdSubscriptions,
        PathValues.API_V1_ROLES_ROLE_TYPE_OR_ROLE_ID_SUBSCRIPTIONS_NOTIFICATION_TYPE: ApiV1RolesRoleTypeOrRoleIdSubscriptionsNotificationType,
        PathValues.API_V1_ROLES_ROLE_TYPE_OR_ROLE_ID_SUBSCRIPTIONS_NOTIFICATION_TYPE_SUBSCRIBE: ApiV1RolesRoleTypeOrRoleIdSubscriptionsNotificationTypeSubscribe,
        PathValues.API_V1_ROLES_ROLE_TYPE_OR_ROLE_ID_SUBSCRIPTIONS_NOTIFICATION_TYPE_UNSUBSCRIBE: ApiV1RolesRoleTypeOrRoleIdSubscriptionsNotificationTypeUnsubscribe,
        PathValues.API_V1_SESSIONS: ApiV1Sessions,
        PathValues.API_V1_SESSIONS_SESSION_ID: ApiV1SessionsSessionId,
        PathValues.API_V1_SESSIONS_SESSION_ID_LIFECYCLE_REFRESH: ApiV1SessionsSessionIdLifecycleRefresh,
        PathValues.API_V1_TEMPLATES_SMS: ApiV1TemplatesSms,
        PathValues.API_V1_TEMPLATES_SMS_TEMPLATE_ID: ApiV1TemplatesSmsTemplateId,
        PathValues.API_V1_THREATS_CONFIGURATION: ApiV1ThreatsConfiguration,
        PathValues.API_V1_TRUSTED_ORIGINS: ApiV1TrustedOrigins,
        PathValues.API_V1_TRUSTED_ORIGINS_TRUSTED_ORIGIN_ID: ApiV1TrustedOriginsTrustedOriginId,
        PathValues.API_V1_TRUSTED_ORIGINS_TRUSTED_ORIGIN_ID_LIFECYCLE_ACTIVATE: ApiV1TrustedOriginsTrustedOriginIdLifecycleActivate,
        PathValues.API_V1_TRUSTED_ORIGINS_TRUSTED_ORIGIN_ID_LIFECYCLE_DEACTIVATE: ApiV1TrustedOriginsTrustedOriginIdLifecycleDeactivate,
        PathValues.API_V1_USERS: ApiV1Users,
        PathValues.API_V1_USERS_ASSOCIATED_USER_ID_LINKED_OBJECTS_PRIMARY_RELATIONSHIP_NAME_PRIMARY_USER_ID: ApiV1UsersAssociatedUserIdLinkedObjectsPrimaryRelationshipNamePrimaryUserId,
        PathValues.API_V1_USERS_USER_ID: ApiV1UsersUserId,
        PathValues.API_V1_USERS_USER_ID_APP_LINKS: ApiV1UsersUserIdAppLinks,
        PathValues.API_V1_USERS_USER_ID_CLIENTS: ApiV1UsersUserIdClients,
        PathValues.API_V1_USERS_USER_ID_CLIENTS_CLIENT_ID_GRANTS: ApiV1UsersUserIdClientsClientIdGrants,
        PathValues.API_V1_USERS_USER_ID_CLIENTS_CLIENT_ID_TOKENS: ApiV1UsersUserIdClientsClientIdTokens,
        PathValues.API_V1_USERS_USER_ID_CLIENTS_CLIENT_ID_TOKENS_TOKEN_ID: ApiV1UsersUserIdClientsClientIdTokensTokenId,
        PathValues.API_V1_USERS_USER_ID_CREDENTIALS_CHANGE_PASSWORD: ApiV1UsersUserIdCredentialsChangePassword,
        PathValues.API_V1_USERS_USER_ID_CREDENTIALS_CHANGE_RECOVERY_QUESTION: ApiV1UsersUserIdCredentialsChangeRecoveryQuestion,
        PathValues.API_V1_USERS_USER_ID_CREDENTIALS_FORGOT_PASSWORD: ApiV1UsersUserIdCredentialsForgotPassword,
        PathValues.API_V1_USERS_USER_ID_FACTORS: ApiV1UsersUserIdFactors,
        PathValues.API_V1_USERS_USER_ID_FACTORS_CATALOG: ApiV1UsersUserIdFactorsCatalog,
        PathValues.API_V1_USERS_USER_ID_FACTORS_QUESTIONS: ApiV1UsersUserIdFactorsQuestions,
        PathValues.API_V1_USERS_USER_ID_FACTORS_FACTOR_ID: ApiV1UsersUserIdFactorsFactorId,
        PathValues.API_V1_USERS_USER_ID_FACTORS_FACTOR_ID_LIFECYCLE_ACTIVATE: ApiV1UsersUserIdFactorsFactorIdLifecycleActivate,
        PathValues.API_V1_USERS_USER_ID_FACTORS_FACTOR_ID_TRANSACTIONS_TRANSACTION_ID: ApiV1UsersUserIdFactorsFactorIdTransactionsTransactionId,
        PathValues.API_V1_USERS_USER_ID_FACTORS_FACTOR_ID_VERIFY: ApiV1UsersUserIdFactorsFactorIdVerify,
        PathValues.API_V1_USERS_USER_ID_GRANTS: ApiV1UsersUserIdGrants,
        PathValues.API_V1_USERS_USER_ID_GRANTS_GRANT_ID: ApiV1UsersUserIdGrantsGrantId,
        PathValues.API_V1_USERS_USER_ID_GROUPS: ApiV1UsersUserIdGroups,
        PathValues.API_V1_USERS_USER_ID_IDPS: ApiV1UsersUserIdIdps,
        PathValues.API_V1_USERS_USER_ID_LIFECYCLE_ACTIVATE: ApiV1UsersUserIdLifecycleActivate,
        PathValues.API_V1_USERS_USER_ID_LIFECYCLE_DEACTIVATE: ApiV1UsersUserIdLifecycleDeactivate,
        PathValues.API_V1_USERS_USER_ID_LIFECYCLE_EXPIRE_PASSWORDTEMP_PASSWORDFALSE: ApiV1UsersUserIdLifecycleExpirePasswordtempPasswordfalse,
        PathValues.API_V1_USERS_USER_ID_LIFECYCLE_EXPIRE_PASSWORDTEMP_PASSWORDTRUE: ApiV1UsersUserIdLifecycleExpirePasswordtempPasswordtrue,
        PathValues.API_V1_USERS_USER_ID_LIFECYCLE_REACTIVATE: ApiV1UsersUserIdLifecycleReactivate,
        PathValues.API_V1_USERS_USER_ID_LIFECYCLE_RESET_FACTORS: ApiV1UsersUserIdLifecycleResetFactors,
        PathValues.API_V1_USERS_USER_ID_LIFECYCLE_RESET_PASSWORD: ApiV1UsersUserIdLifecycleResetPassword,
        PathValues.API_V1_USERS_USER_ID_LIFECYCLE_SUSPEND: ApiV1UsersUserIdLifecycleSuspend,
        PathValues.API_V1_USERS_USER_ID_LIFECYCLE_UNLOCK: ApiV1UsersUserIdLifecycleUnlock,
        PathValues.API_V1_USERS_USER_ID_LIFECYCLE_UNSUSPEND: ApiV1UsersUserIdLifecycleUnsuspend,
        PathValues.API_V1_USERS_USER_ID_LINKED_OBJECTS_RELATIONSHIP_NAME: ApiV1UsersUserIdLinkedObjectsRelationshipName,
        PathValues.API_V1_USERS_USER_ID_ROLES: ApiV1UsersUserIdRoles,
        PathValues.API_V1_USERS_USER_ID_ROLES_ROLE_ID: ApiV1UsersUserIdRolesRoleId,
        PathValues.API_V1_USERS_USER_ID_ROLES_ROLE_ID_TARGETS_CATALOG_APPS: ApiV1UsersUserIdRolesRoleIdTargetsCatalogApps,
        PathValues.API_V1_USERS_USER_ID_ROLES_ROLE_ID_TARGETS_CATALOG_APPS_APP_NAME: ApiV1UsersUserIdRolesRoleIdTargetsCatalogAppsAppName,
        PathValues.API_V1_USERS_USER_ID_ROLES_ROLE_ID_TARGETS_CATALOG_APPS_APP_NAME_APPLICATION_ID: ApiV1UsersUserIdRolesRoleIdTargetsCatalogAppsAppNameApplicationId,
        PathValues.API_V1_USERS_USER_ID_ROLES_ROLE_ID_TARGETS_GROUPS: ApiV1UsersUserIdRolesRoleIdTargetsGroups,
        PathValues.API_V1_USERS_USER_ID_ROLES_ROLE_ID_TARGETS_GROUPS_GROUP_ID: ApiV1UsersUserIdRolesRoleIdTargetsGroupsGroupId,
        PathValues.API_V1_USERS_USER_ID_SESSIONS: ApiV1UsersUserIdSessions,
        PathValues.API_V1_USERS_USER_ID_SUBSCRIPTIONS: ApiV1UsersUserIdSubscriptions,
        PathValues.API_V1_USERS_USER_ID_SUBSCRIPTIONS_NOTIFICATION_TYPE: ApiV1UsersUserIdSubscriptionsNotificationType,
        PathValues.API_V1_USERS_USER_ID_SUBSCRIPTIONS_NOTIFICATION_TYPE_SUBSCRIBE: ApiV1UsersUserIdSubscriptionsNotificationTypeSubscribe,
        PathValues.API_V1_USERS_USER_ID_SUBSCRIPTIONS_NOTIFICATION_TYPE_UNSUBSCRIBE: ApiV1UsersUserIdSubscriptionsNotificationTypeUnsubscribe,
        PathValues.API_V1_ZONES: ApiV1Zones,
        PathValues.API_V1_ZONES_ZONE_ID: ApiV1ZonesZoneId,
        PathValues.API_V1_ZONES_ZONE_ID_LIFECYCLE_ACTIVATE: ApiV1ZonesZoneIdLifecycleActivate,
        PathValues.API_V1_ZONES_ZONE_ID_LIFECYCLE_DEACTIVATE: ApiV1ZonesZoneIdLifecycleDeactivate,
    }
)
