# coding: utf-8

"""
    Okta API

    Allows customers to easily access the Okta API

    The version of the OpenAPI document: 2.16.0
    Contact: devex-public@okta.com
    Created by: https://developer.okta.com/
"""

from datetime import date, datetime  # noqa: F401
import decimal  # noqa: F401
import functools  # noqa: F401
import io  # noqa: F401
import re  # noqa: F401
import typing  # noqa: F401
import typing_extensions  # noqa: F401
import uuid  # noqa: F401

import frozendict  # noqa: F401

from okta_python_sdk import schemas  # noqa: F401


class ApplicationAccessibility(
    schemas.DictSchema
):
    """
    This class is auto generated by Konfig (https://konfigthis.com)
    """


    class MetaOapg:
        
        class properties:
            errorRedirectUrl = schemas.StrSchema
            loginRedirectUrl = schemas.StrSchema
            selfService = schemas.BoolSchema
            __annotations__ = {
                "errorRedirectUrl": errorRedirectUrl,
                "loginRedirectUrl": loginRedirectUrl,
                "selfService": selfService,
            }
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["errorRedirectUrl"]) -> MetaOapg.properties.errorRedirectUrl: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["loginRedirectUrl"]) -> MetaOapg.properties.loginRedirectUrl: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["selfService"]) -> MetaOapg.properties.selfService: ...
    
    @typing.overload
    def __getitem__(self, name: str) -> schemas.UnsetAnyTypeSchema: ...
    
    def __getitem__(self, name: typing.Union[typing_extensions.Literal["errorRedirectUrl", "loginRedirectUrl", "selfService", ], str]):
        # dict_instance[name] accessor
        return super().__getitem__(name)
    
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["errorRedirectUrl"]) -> typing.Union[MetaOapg.properties.errorRedirectUrl, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["loginRedirectUrl"]) -> typing.Union[MetaOapg.properties.loginRedirectUrl, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["selfService"]) -> typing.Union[MetaOapg.properties.selfService, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: str) -> typing.Union[schemas.UnsetAnyTypeSchema, schemas.Unset]: ...
    
    def get_item_oapg(self, name: typing.Union[typing_extensions.Literal["errorRedirectUrl", "loginRedirectUrl", "selfService", ], str]):
        return super().get_item_oapg(name)
    

    def __new__(
        cls,
        *args: typing.Union[dict, frozendict.frozendict, ],
        errorRedirectUrl: typing.Union[MetaOapg.properties.errorRedirectUrl, str, schemas.Unset] = schemas.unset,
        loginRedirectUrl: typing.Union[MetaOapg.properties.loginRedirectUrl, str, schemas.Unset] = schemas.unset,
        selfService: typing.Union[MetaOapg.properties.selfService, bool, schemas.Unset] = schemas.unset,
        _configuration: typing.Optional[schemas.Configuration] = None,
        **kwargs: typing.Union[schemas.AnyTypeSchema, dict, frozendict.frozendict, str, date, datetime, uuid.UUID, int, float, decimal.Decimal, None, list, tuple, bytes],
    ) -> 'ApplicationAccessibility':
        return super().__new__(
            cls,
            *args,
            errorRedirectUrl=errorRedirectUrl,
            loginRedirectUrl=loginRedirectUrl,
            selfService=selfService,
            _configuration=_configuration,
            **kwargs,
        )
