# coding: utf-8

"""
    Okta API

    Allows customers to easily access the Okta API

    The version of the OpenAPI document: 2.16.0
    Contact: devex-public@okta.com
    Created by: https://developer.okta.com/
"""

from datetime import date, datetime  # noqa: F401
import decimal  # noqa: F401
import functools  # noqa: F401
import io  # noqa: F401
import re  # noqa: F401
import typing  # noqa: F401
import typing_extensions  # noqa: F401
import uuid  # noqa: F401

import frozendict  # noqa: F401

from okta_python_sdk import schemas  # noqa: F401


class AuthenticatorType(
    schemas.EnumBase,
    schemas.StrSchema
):
    """
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    
    @schemas.classproperty
    def APP(cls):
        return cls("app")
    
    @schemas.classproperty
    def PASSWORD(cls):
        return cls("password")
    
    @schemas.classproperty
    def SECURITY_QUESTION(cls):
        return cls("security_question")
    
    @schemas.classproperty
    def PHONE(cls):
        return cls("phone")
    
    @schemas.classproperty
    def EMAIL(cls):
        return cls("email")
    
    @schemas.classproperty
    def SECURITY_KEY(cls):
        return cls("security_key")
    
    @schemas.classproperty
    def FEDERATED(cls):
        return cls("federated")
