# coding: utf-8

"""
    Okta API

    Allows customers to easily access the Okta API

    The version of the OpenAPI document: 2.16.0
    Contact: devex-public@okta.com
    Created by: https://developer.okta.com/
"""

from datetime import date, datetime  # noqa: F401
import decimal  # noqa: F401
import functools  # noqa: F401
import io  # noqa: F401
import re  # noqa: F401
import typing  # noqa: F401
import typing_extensions  # noqa: F401
import uuid  # noqa: F401

import frozendict  # noqa: F401

from okta_python_sdk import schemas  # noqa: F401


class FactorProvider(
    schemas.EnumBase,
    schemas.StrSchema
):
    """
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    
    @schemas.classproperty
    def OKTA(cls):
        return cls("OKTA")
    
    @schemas.classproperty
    def RSA(cls):
        return cls("RSA")
    
    @schemas.classproperty
    def FIDO(cls):
        return cls("FIDO")
    
    @schemas.classproperty
    def GOOGLE(cls):
        return cls("GOOGLE")
    
    @schemas.classproperty
    def SYMANTEC(cls):
        return cls("SYMANTEC")
    
    @schemas.classproperty
    def DUO(cls):
        return cls("DUO")
    
    @schemas.classproperty
    def YUBICO(cls):
        return cls("YUBICO")
    
    @schemas.classproperty
    def CUSTOM(cls):
        return cls("CUSTOM")
    
    @schemas.classproperty
    def APPLE(cls):
        return cls("APPLE")
