# coding: utf-8

"""
    Okta API

    Allows customers to easily access the Okta API

    The version of the OpenAPI document: 2.16.0
    Contact: devex-public@okta.com
    Created by: https://developer.okta.com/
"""

from datetime import date, datetime  # noqa: F401
import decimal  # noqa: F401
import functools  # noqa: F401
import io  # noqa: F401
import re  # noqa: F401
import typing  # noqa: F401
import typing_extensions  # noqa: F401
import uuid  # noqa: F401

import frozendict  # noqa: F401

from okta_python_sdk import schemas  # noqa: F401


class IdentityProviderPolicyRuleCondition(
    schemas.DictSchema
):
    """
    This class is auto generated by Konfig (https://konfigthis.com)
    """


    class MetaOapg:
        
        class properties:
        
            @staticmethod
            def idpIds() -> typing.Type['IdentityProviderPolicyRuleConditionIdpIds']:
                return IdentityProviderPolicyRuleConditionIdpIds
            
            
            class provider(
                schemas.EnumBase,
                schemas.StrSchema
            ):
                
                @schemas.classproperty
                def ANY(cls):
                    return cls("ANY")
                
                @schemas.classproperty
                def OKTA(cls):
                    return cls("OKTA")
                
                @schemas.classproperty
                def SPECIFIC_IDP(cls):
                    return cls("SPECIFIC_IDP")
            __annotations__ = {
                "idpIds": idpIds,
                "provider": provider,
            }
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["idpIds"]) -> 'IdentityProviderPolicyRuleConditionIdpIds': ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["provider"]) -> MetaOapg.properties.provider: ...
    
    @typing.overload
    def __getitem__(self, name: str) -> schemas.UnsetAnyTypeSchema: ...
    
    def __getitem__(self, name: typing.Union[typing_extensions.Literal["idpIds", "provider", ], str]):
        # dict_instance[name] accessor
        return super().__getitem__(name)
    
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["idpIds"]) -> typing.Union['IdentityProviderPolicyRuleConditionIdpIds', schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["provider"]) -> typing.Union[MetaOapg.properties.provider, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: str) -> typing.Union[schemas.UnsetAnyTypeSchema, schemas.Unset]: ...
    
    def get_item_oapg(self, name: typing.Union[typing_extensions.Literal["idpIds", "provider", ], str]):
        return super().get_item_oapg(name)
    

    def __new__(
        cls,
        *args: typing.Union[dict, frozendict.frozendict, ],
        idpIds: typing.Union['IdentityProviderPolicyRuleConditionIdpIds', schemas.Unset] = schemas.unset,
        provider: typing.Union[MetaOapg.properties.provider, str, schemas.Unset] = schemas.unset,
        _configuration: typing.Optional[schemas.Configuration] = None,
        **kwargs: typing.Union[schemas.AnyTypeSchema, dict, frozendict.frozendict, str, date, datetime, uuid.UUID, int, float, decimal.Decimal, None, list, tuple, bytes],
    ) -> 'IdentityProviderPolicyRuleCondition':
        return super().__new__(
            cls,
            *args,
            idpIds=idpIds,
            provider=provider,
            _configuration=_configuration,
            **kwargs,
        )

from okta_python_sdk.model.identity_provider_policy_rule_condition_idp_ids import IdentityProviderPolicyRuleConditionIdpIds
