# coding: utf-8

"""
    Okta API

    Allows customers to easily access the Okta API

    The version of the OpenAPI document: 2.16.0
    Contact: devex-public@okta.com
    Created by: https://developer.okta.com/
"""

from datetime import date, datetime  # noqa: F401
import decimal  # noqa: F401
import functools  # noqa: F401
import io  # noqa: F401
import re  # noqa: F401
import typing  # noqa: F401
import typing_extensions  # noqa: F401
import uuid  # noqa: F401

import frozendict  # noqa: F401

from okta_python_sdk import schemas  # noqa: F401


class InlineHookType(
    schemas.EnumBase,
    schemas.StrSchema
):
    """
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    
    @schemas.classproperty
    def OAUTH2_TOKENS_TRANSFORM(cls):
        return cls("com.okta.oauth2.tokens.transform")
    
    @schemas.classproperty
    def IMPORT_TRANSFORM(cls):
        return cls("com.okta.import.transform")
    
    @schemas.classproperty
    def SAML_TOKENS_TRANSFORM(cls):
        return cls("com.okta.saml.tokens.transform")
    
    @schemas.classproperty
    def USER_PREREGISTRATION(cls):
        return cls("com.okta.user.pre-registration")
    
    @schemas.classproperty
    def USER_CREDENTIAL_PASSWORD_IMPORT(cls):
        return cls("com.okta.user.credential.password.import")
