# coding: utf-8

"""
    Okta API

    Allows customers to easily access the Okta API

    The version of the OpenAPI document: 2.16.0
    Contact: devex-public@okta.com
    Created by: https://developer.okta.com/
"""

from datetime import date, datetime  # noqa: F401
import decimal  # noqa: F401
import functools  # noqa: F401
import io  # noqa: F401
import re  # noqa: F401
import typing  # noqa: F401
import typing_extensions  # noqa: F401
import uuid  # noqa: F401

import frozendict  # noqa: F401

from okta_python_sdk import schemas  # noqa: F401


class LogUserAgent(
    schemas.DictSchema
):
    """
    This class is auto generated by Konfig (https://konfigthis.com)
    """


    class MetaOapg:
        
        class properties:
            browser = schemas.StrSchema
            os = schemas.StrSchema
            rawUserAgent = schemas.StrSchema
            __annotations__ = {
                "browser": browser,
                "os": os,
                "rawUserAgent": rawUserAgent,
            }
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["browser"]) -> MetaOapg.properties.browser: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["os"]) -> MetaOapg.properties.os: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["rawUserAgent"]) -> MetaOapg.properties.rawUserAgent: ...
    
    @typing.overload
    def __getitem__(self, name: str) -> schemas.UnsetAnyTypeSchema: ...
    
    def __getitem__(self, name: typing.Union[typing_extensions.Literal["browser", "os", "rawUserAgent", ], str]):
        # dict_instance[name] accessor
        return super().__getitem__(name)
    
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["browser"]) -> typing.Union[MetaOapg.properties.browser, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["os"]) -> typing.Union[MetaOapg.properties.os, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["rawUserAgent"]) -> typing.Union[MetaOapg.properties.rawUserAgent, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: str) -> typing.Union[schemas.UnsetAnyTypeSchema, schemas.Unset]: ...
    
    def get_item_oapg(self, name: typing.Union[typing_extensions.Literal["browser", "os", "rawUserAgent", ], str]):
        return super().get_item_oapg(name)
    

    def __new__(
        cls,
        *args: typing.Union[dict, frozendict.frozendict, ],
        browser: typing.Union[MetaOapg.properties.browser, str, schemas.Unset] = schemas.unset,
        os: typing.Union[MetaOapg.properties.os, str, schemas.Unset] = schemas.unset,
        rawUserAgent: typing.Union[MetaOapg.properties.rawUserAgent, str, schemas.Unset] = schemas.unset,
        _configuration: typing.Optional[schemas.Configuration] = None,
        **kwargs: typing.Union[schemas.AnyTypeSchema, dict, frozendict.frozendict, str, date, datetime, uuid.UUID, int, float, decimal.Decimal, None, list, tuple, bytes],
    ) -> 'LogUserAgent':
        return super().__new__(
            cls,
            *args,
            browser=browser,
            os=os,
            rawUserAgent=rawUserAgent,
            _configuration=_configuration,
            **kwargs,
        )
