# coding: utf-8

"""
    Okta API

    Allows customers to easily access the Okta API

    The version of the OpenAPI document: 2.16.0
    Contact: devex-public@okta.com
    Created by: https://developer.okta.com/
"""

from datetime import date, datetime  # noqa: F401
import decimal  # noqa: F401
import functools  # noqa: F401
import io  # noqa: F401
import re  # noqa: F401
import typing  # noqa: F401
import typing_extensions  # noqa: F401
import uuid  # noqa: F401

import frozendict  # noqa: F401

from okta_python_sdk import schemas  # noqa: F401


class MDMEnrollmentPolicyRuleCondition(
    schemas.DictSchema
):
    """
    This class is auto generated by Konfig (https://konfigthis.com)
    """


    class MetaOapg:
        
        class properties:
            blockNonSafeAndroid = schemas.BoolSchema
            
            
            class enrollment(
                schemas.EnumBase,
                schemas.StrSchema
            ):
                
                @schemas.classproperty
                def OMM(cls):
                    return cls("OMM")
                
                @schemas.classproperty
                def ANY_OR_NONE(cls):
                    return cls("ANY_OR_NONE")
            __annotations__ = {
                "blockNonSafeAndroid": blockNonSafeAndroid,
                "enrollment": enrollment,
            }
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["blockNonSafeAndroid"]) -> MetaOapg.properties.blockNonSafeAndroid: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["enrollment"]) -> MetaOapg.properties.enrollment: ...
    
    @typing.overload
    def __getitem__(self, name: str) -> schemas.UnsetAnyTypeSchema: ...
    
    def __getitem__(self, name: typing.Union[typing_extensions.Literal["blockNonSafeAndroid", "enrollment", ], str]):
        # dict_instance[name] accessor
        return super().__getitem__(name)
    
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["blockNonSafeAndroid"]) -> typing.Union[MetaOapg.properties.blockNonSafeAndroid, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["enrollment"]) -> typing.Union[MetaOapg.properties.enrollment, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: str) -> typing.Union[schemas.UnsetAnyTypeSchema, schemas.Unset]: ...
    
    def get_item_oapg(self, name: typing.Union[typing_extensions.Literal["blockNonSafeAndroid", "enrollment", ], str]):
        return super().get_item_oapg(name)
    

    def __new__(
        cls,
        *args: typing.Union[dict, frozendict.frozendict, ],
        blockNonSafeAndroid: typing.Union[MetaOapg.properties.blockNonSafeAndroid, bool, schemas.Unset] = schemas.unset,
        enrollment: typing.Union[MetaOapg.properties.enrollment, str, schemas.Unset] = schemas.unset,
        _configuration: typing.Optional[schemas.Configuration] = None,
        **kwargs: typing.Union[schemas.AnyTypeSchema, dict, frozendict.frozendict, str, date, datetime, uuid.UUID, int, float, decimal.Decimal, None, list, tuple, bytes],
    ) -> 'MDMEnrollmentPolicyRuleCondition':
        return super().__new__(
            cls,
            *args,
            blockNonSafeAndroid=blockNonSafeAndroid,
            enrollment=enrollment,
            _configuration=_configuration,
            **kwargs,
        )
