# coding: utf-8

"""
    Okta API

    Allows customers to easily access the Okta API

    The version of the OpenAPI document: 2.16.0
    Contact: devex-public@okta.com
    Created by: https://developer.okta.com/
"""

from datetime import date, datetime  # noqa: F401
import decimal  # noqa: F401
import functools  # noqa: F401
import io  # noqa: F401
import re  # noqa: F401
import typing  # noqa: F401
import typing_extensions  # noqa: F401
import uuid  # noqa: F401

import frozendict  # noqa: F401

from okta_python_sdk import schemas  # noqa: F401


class UserSchemaAttributeMaster(
    schemas.DictSchema
):
    """
    This class is auto generated by Konfig (https://konfigthis.com)
    """


    class MetaOapg:
        
        class properties:
            
            
            class priority(
                schemas.ListSchema
            ):
            
            
                class MetaOapg:
                    
                    @staticmethod
                    def items() -> typing.Type['UserSchemaAttributeMasterPriority']:
                        return UserSchemaAttributeMasterPriority
            
                def __new__(
                    cls,
                    arg: typing.Union[typing.Tuple['UserSchemaAttributeMasterPriority'], typing.List['UserSchemaAttributeMasterPriority']],
                    _configuration: typing.Optional[schemas.Configuration] = None,
                ) -> 'priority':
                    return super().__new__(
                        cls,
                        arg,
                        _configuration=_configuration,
                    )
            
                def __getitem__(self, i: int) -> 'UserSchemaAttributeMasterPriority':
                    return super().__getitem__(i)
        
            @staticmethod
            def type() -> typing.Type['UserSchemaAttributeMasterType']:
                return UserSchemaAttributeMasterType
            __annotations__ = {
                "priority": priority,
                "type": type,
            }
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["priority"]) -> MetaOapg.properties.priority: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["type"]) -> 'UserSchemaAttributeMasterType': ...
    
    @typing.overload
    def __getitem__(self, name: str) -> schemas.UnsetAnyTypeSchema: ...
    
    def __getitem__(self, name: typing.Union[typing_extensions.Literal["priority", "type", ], str]):
        # dict_instance[name] accessor
        return super().__getitem__(name)
    
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["priority"]) -> typing.Union[MetaOapg.properties.priority, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["type"]) -> typing.Union['UserSchemaAttributeMasterType', schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: str) -> typing.Union[schemas.UnsetAnyTypeSchema, schemas.Unset]: ...
    
    def get_item_oapg(self, name: typing.Union[typing_extensions.Literal["priority", "type", ], str]):
        return super().get_item_oapg(name)
    

    def __new__(
        cls,
        *args: typing.Union[dict, frozendict.frozendict, ],
        priority: typing.Union[MetaOapg.properties.priority, list, tuple, schemas.Unset] = schemas.unset,
        type: typing.Union['UserSchemaAttributeMasterType', schemas.Unset] = schemas.unset,
        _configuration: typing.Optional[schemas.Configuration] = None,
        **kwargs: typing.Union[schemas.AnyTypeSchema, dict, frozendict.frozendict, str, date, datetime, uuid.UUID, int, float, decimal.Decimal, None, list, tuple, bytes],
    ) -> 'UserSchemaAttributeMaster':
        return super().__new__(
            cls,
            *args,
            priority=priority,
            type=type,
            _configuration=_configuration,
            **kwargs,
        )

from okta_python_sdk.model.user_schema_attribute_master_priority import UserSchemaAttributeMasterPriority
from okta_python_sdk.model.user_schema_attribute_master_type import UserSchemaAttributeMasterType
