# coding: utf-8

"""
    Okta API

    Allows customers to easily access the Okta API

    The version of the OpenAPI document: 2.16.0
    Contact: devex-public@okta.com
    Created by: https://developer.okta.com/
"""

from datetime import date, datetime  # noqa: F401
import decimal  # noqa: F401
import functools  # noqa: F401
import io  # noqa: F401
import re  # noqa: F401
import typing  # noqa: F401
import typing_extensions  # noqa: F401
import uuid  # noqa: F401

import frozendict  # noqa: F401

from okta_python_sdk import schemas  # noqa: F401


class UserCredentials(
    schemas.DictSchema
):
    """
    This class is auto generated by Konfig (https://konfigthis.com)
    """


    class MetaOapg:
        
        class properties:
        
            @staticmethod
            def password() -> typing.Type['PasswordCredential']:
                return PasswordCredential
        
            @staticmethod
            def provider() -> typing.Type['AuthenticationProvider']:
                return AuthenticationProvider
        
            @staticmethod
            def recovery_question() -> typing.Type['RecoveryQuestionCredential']:
                return RecoveryQuestionCredential
            __annotations__ = {
                "password": password,
                "provider": provider,
                "recovery_question": recovery_question,
            }
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["password"]) -> 'PasswordCredential': ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["provider"]) -> 'AuthenticationProvider': ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["recovery_question"]) -> 'RecoveryQuestionCredential': ...
    
    @typing.overload
    def __getitem__(self, name: str) -> schemas.UnsetAnyTypeSchema: ...
    
    def __getitem__(self, name: typing.Union[typing_extensions.Literal["password", "provider", "recovery_question", ], str]):
        # dict_instance[name] accessor
        return super().__getitem__(name)
    
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["password"]) -> typing.Union['PasswordCredential', schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["provider"]) -> typing.Union['AuthenticationProvider', schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["recovery_question"]) -> typing.Union['RecoveryQuestionCredential', schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: str) -> typing.Union[schemas.UnsetAnyTypeSchema, schemas.Unset]: ...
    
    def get_item_oapg(self, name: typing.Union[typing_extensions.Literal["password", "provider", "recovery_question", ], str]):
        return super().get_item_oapg(name)
    

    def __new__(
        cls,
        *args: typing.Union[dict, frozendict.frozendict, ],
        password: typing.Union['PasswordCredential', schemas.Unset] = schemas.unset,
        provider: typing.Union['AuthenticationProvider', schemas.Unset] = schemas.unset,
        recovery_question: typing.Union['RecoveryQuestionCredential', schemas.Unset] = schemas.unset,
        _configuration: typing.Optional[schemas.Configuration] = None,
        **kwargs: typing.Union[schemas.AnyTypeSchema, dict, frozendict.frozendict, str, date, datetime, uuid.UUID, int, float, decimal.Decimal, None, list, tuple, bytes],
    ) -> 'UserCredentials':
        return super().__new__(
            cls,
            *args,
            password=password,
            provider=provider,
            recovery_question=recovery_question,
            _configuration=_configuration,
            **kwargs,
        )

from okta_python_sdk.model.authentication_provider import AuthenticationProvider
from okta_python_sdk.model.password_credential import PasswordCredential
from okta_python_sdk.model.recovery_question_credential import RecoveryQuestionCredential
