# coding: utf-8

"""
    Okta API

    Allows customers to easily access the Okta API

    The version of the OpenAPI document: 2.16.0
    Contact: devex-public@okta.com
    Created by: https://developer.okta.com/
"""

from datetime import date, datetime  # noqa: F401
import decimal  # noqa: F401
import functools  # noqa: F401
import io  # noqa: F401
import re  # noqa: F401
import typing  # noqa: F401
import typing_extensions  # noqa: F401
import uuid  # noqa: F401

import frozendict  # noqa: F401

from okta_python_sdk import schemas  # noqa: F401


class VerificationMethod(
    schemas.DictSchema
):
    """
    This class is auto generated by Konfig (https://konfigthis.com)
    """


    class MetaOapg:
        
        class properties:
            
            
            class constraints(
                schemas.ListSchema
            ):
            
            
                class MetaOapg:
                    
                    @staticmethod
                    def items() -> typing.Type['AccessPolicyConstraints']:
                        return AccessPolicyConstraints
            
                def __new__(
                    cls,
                    arg: typing.Union[typing.Tuple['AccessPolicyConstraints'], typing.List['AccessPolicyConstraints']],
                    _configuration: typing.Optional[schemas.Configuration] = None,
                ) -> 'constraints':
                    return super().__new__(
                        cls,
                        arg,
                        _configuration=_configuration,
                    )
            
                def __getitem__(self, i: int) -> 'AccessPolicyConstraints':
                    return super().__getitem__(i)
            factorMode = schemas.StrSchema
            inactivityPeriod = schemas.StrSchema
            reauthenticateIn = schemas.StrSchema
            type = schemas.StrSchema
            __annotations__ = {
                "constraints": constraints,
                "factorMode": factorMode,
                "inactivityPeriod": inactivityPeriod,
                "reauthenticateIn": reauthenticateIn,
                "type": type,
            }
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["constraints"]) -> MetaOapg.properties.constraints: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["factorMode"]) -> MetaOapg.properties.factorMode: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["inactivityPeriod"]) -> MetaOapg.properties.inactivityPeriod: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["reauthenticateIn"]) -> MetaOapg.properties.reauthenticateIn: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["type"]) -> MetaOapg.properties.type: ...
    
    @typing.overload
    def __getitem__(self, name: str) -> schemas.UnsetAnyTypeSchema: ...
    
    def __getitem__(self, name: typing.Union[typing_extensions.Literal["constraints", "factorMode", "inactivityPeriod", "reauthenticateIn", "type", ], str]):
        # dict_instance[name] accessor
        return super().__getitem__(name)
    
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["constraints"]) -> typing.Union[MetaOapg.properties.constraints, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["factorMode"]) -> typing.Union[MetaOapg.properties.factorMode, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["inactivityPeriod"]) -> typing.Union[MetaOapg.properties.inactivityPeriod, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["reauthenticateIn"]) -> typing.Union[MetaOapg.properties.reauthenticateIn, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["type"]) -> typing.Union[MetaOapg.properties.type, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: str) -> typing.Union[schemas.UnsetAnyTypeSchema, schemas.Unset]: ...
    
    def get_item_oapg(self, name: typing.Union[typing_extensions.Literal["constraints", "factorMode", "inactivityPeriod", "reauthenticateIn", "type", ], str]):
        return super().get_item_oapg(name)
    

    def __new__(
        cls,
        *args: typing.Union[dict, frozendict.frozendict, ],
        constraints: typing.Union[MetaOapg.properties.constraints, list, tuple, schemas.Unset] = schemas.unset,
        factorMode: typing.Union[MetaOapg.properties.factorMode, str, schemas.Unset] = schemas.unset,
        inactivityPeriod: typing.Union[MetaOapg.properties.inactivityPeriod, str, schemas.Unset] = schemas.unset,
        reauthenticateIn: typing.Union[MetaOapg.properties.reauthenticateIn, str, schemas.Unset] = schemas.unset,
        type: typing.Union[MetaOapg.properties.type, str, schemas.Unset] = schemas.unset,
        _configuration: typing.Optional[schemas.Configuration] = None,
        **kwargs: typing.Union[schemas.AnyTypeSchema, dict, frozendict.frozendict, str, date, datetime, uuid.UUID, int, float, decimal.Decimal, None, list, tuple, bytes],
    ) -> 'VerificationMethod':
        return super().__new__(
            cls,
            *args,
            constraints=constraints,
            factorMode=factorMode,
            inactivityPeriod=inactivityPeriod,
            reauthenticateIn=reauthenticateIn,
            type=type,
            _configuration=_configuration,
            **kwargs,
        )

from okta_python_sdk.model.access_policy_constraints import AccessPolicyConstraints
