from okta_python_sdk.paths.api_v1_authorization_servers_auth_server_id_policies_policy_id_rules_rule_id_lifecycle_deactivate.post import ApiForpost


class ApiV1AuthorizationServersAuthServerIdPoliciesPolicyIdRulesRuleIdLifecycleDeactivate(
    ApiForpost,
):
    pass
